In [64]:
import pandas as pd
import chardet
import numpy as np

In [65]:
with open('extract_07022024-base_source.csv', 'rb') as f:
    result = chardet.detect(f.read())
    encoding = result['encoding']

print("Encodage détecté:", encoding)

Encodage détecté: Windows-1254

In [153]:
#referentiel base source
source_entreprise=pd.read_csv('extract_07022024-base_source.csv', encoding='utf-8', sep=',', on_bad_lines='skip')
source_entreprise.shape

C:\Users\chris\AppData\Local\Temp\ipykernel_30512\3033168289.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  source_entreprise=pd.read_csv('extract_07022024-base_source.csv', encoding='utf-8', sep=',', on_bad_lines='skip')

(11147, 179)

In [154]:
def renommer_colbase_source_selectionnees(dataframe, colonnes_a_renommer):
    # Créez un dictionnaire pour mapper les anciens noms aux nouveaux noms
    colonnes_renommees = {}
    for colonne in colonnes_a_renommer:
        nouveau_nom = colonne
        if colonne.startswith("societeinfo_"):
            nouveau_nom = nouveau_nom.replace("societeinfo_", "")
        if colonne.startswith("papers_"):
            nouveau_nom = nouveau_nom.replace("papers_", "")
        colonnes_renommees[colonne] = nouveau_nom
    
    # Utilisez la méthode rename() pour renommer les colonnes sélectionnées du DataFrame
    dataframe = dataframe.rename(columns=colonnes_renommees)
    
    return dataframe
colonnes_a_renommer=['papers_beneficiaires_effectifs','papers_bodacc_important_message',
                     'papers_derniere_mise_a_jour_rcs','papers_derniere_mise_a_jour_sirene',
                     'papers_marques','papers_procedures_collectives','papers_publications_bodacc',
                     'papers_representants','papers_resultat_d_exploitation_2018','papers_resultat_d_exploitation_2019',
                     'papers_resultat_d_exploitation_2020','papers_resultat_d_exploitation_2021',
                     'papers_resultat_d_exploitation_2022','papers_siren','societeinfo_ape_code','societeinfo_ape_name',
                     'societeinfo_capital','societeinfo_commercial_name','societeinfo_company_name',
                     'societeinfo_corporate_object','societeinfo_corporate_officer_birth_date',
                     'societeinfo_corporate_officer_name','societeinfo_corporate_officer_role','societeinfo_creation_date',
                     'societeinfo_current_assets_2018','societeinfo_current_assets_2019',
                     'societeinfo_current_assets_2020','societeinfo_current_assets_2021','societeinfo_current_assets_2022',
                     'societeinfo_current_liabilities_2018','societeinfo_current_liabilities_2019',
                     'societeinfo_current_liabilities_2020','societeinfo_current_liabilities_2021',
                     'societeinfo_current_liabilities_2022','societeinfo_employees_number_for_linkedin',
                     'societeinfo_enrollment','societeinfo_equity_2018','societeinfo_equity_2019',
                     'societeinfo_equity_2020','societeinfo_equity_2021','societeinfo_equity_2022',
                     'societeinfo_facebook_url','societeinfo_glassdoor_avis','societeinfo_glassdoor_notation',
                     'societeinfo_google_business_nb_avis','societeinfo_google_business_notation',
                     'societeinfo_google_business_resultats','societeinfo_google_search_description',
                     'societeinfo_google_search_keyword','societeinfo_greffe_name',
                     'societeinfo_gross_operating_ebitda_2018','societeinfo_gross_operating_ebitda_2019',
                     'societeinfo_gross_operating_ebitda_2020','societeinfo_gross_operating_ebitda_2021',
                     'societeinfo_gross_operating_ebitda_2022','societeinfo_gross_operating_ebitda_ratio_2018',
                     'societeinfo_gross_operating_ebitda_ratio_2019','societeinfo_gross_operating_ebitda_ratio_2020',
                     'societeinfo_gross_operating_ebitda_ratio_2021','societeinfo_gross_operating_ebitda_ratio_2022',
                     'societeinfo_growth_ratio_2019','societeinfo_growth_ratio_2020','societeinfo_growth_ratio_2021',
                     'societeinfo_growth_ratio_022','societeinfo_indeed_about_content','societeinfo_indeed_job_results',
                     'societeinfo_indeed_job_results_count','societeinfo_instagram_url','societeinfo_last_bodacc',
                     'societeinfo_last_number_of_employees','societeinfo_legal_company_form','societeinfo_linkedin_jobs',
                     'societeinfo_linkedin_posts','societeinfo_logo','societeinfo_net_debt_2018',
                     'societeinfo_net_debt_2019','societeinfo_net_debt_2020','societeinfo_net_debt_2021',
                     'societeinfo_net_debt_2022','societeinfo_net_result_2018','societeinfo_net_result_2019',
                     'societeinfo_net_result_2020','societeinfo_net_result_2021','societeinfo_net_result_2022',
                     'societeinfo_opportunities_of_the_siret','societeinfo_postal_address_city',
                     'societeinfo_postal_address_country','societeinfo_postal_address_country_code',
                     'societeinfo_postal_address_lat','societeinfo_postal_address_lng',
                     'societeinfo_postal_address_postal_address_additional_name','societeinfo_postal_address_postal_code',
                     'societeinfo_postal_address_street','societeinfo_range_employee_for_linkedin',
                     'societeinfo_reimbursement_ratio_2018','societeinfo_reimbursement_ratio_2019',
                     'societeinfo_reimbursement_ratio_2020','societeinfo_reimbursement_ratio_2021',
                     'societeinfo_reimbursement_ratio_2022','societeinfo_resultat_exploitation_ratio_2018',
                     'societeinfo_resultat_exploitation_ratio_2019','societeinfo_resultat_exploitation_ratio_2020',
                     'societeinfo_resultat_exploitation_ratio_2021','societeinfo_resultat_exploitation_ratio_2022',
                     'societeinfo_revenue_2018','societeinfo_revenue_2019','societeinfo_revenue_2020',
                     'societeinfo_revenue_2021','societeinfo_revenue_2022','societeinfo_robustness_ratio_2018',
                     'societeinfo_robustness_ratio_2019','societeinfo_robustness_ratio_2020',
                     'societeinfo_robustness_ratio_2021','societeinfo_robustness_ratio_2022','societeinfo_roe_2018',
                     'societeinfo_roe_2019','societeinfo_roe_2020','societeinfo_roe_2021','societeinfo_roe_2022',
                     'societeinfo_siren','societeinfo_siret','societeinfo_solvability_ratio_2018',
                     'societeinfo_solvability_ratio_2019','societeinfo_solvability_ratio_2020',
                     'societeinfo_solvability_ratio_2021','societeinfo_solvability_ratio_2022',
                     'societeinfo_strenghts_of_the_siret','societeinfo_threats_of_the_siret','societeinfo_twitter_url',
                     'societeinfo_vat_number','societeinfo_weaknesses_of_the_siret','societeinfo_web_scrap',
                     'societeinfo_web_site_url']

                     # Appliquer la fonction pour renommer les colonnes
source_entreprise = renommer_colbase_source_selectionnees(source_entreprise, colonnes_a_renommer)

In [155]:
# type d entreprise selon nombre de salariés
def determine_type_ent(enrollment):
    if enrollment < 3:
        return 'microentreprise'
    elif 3 <= enrollment <= 10:
        return 'TPE'
    elif 11 <= enrollment <= 250:
        return 'PME'
    elif 251 <= enrollment <= 5000:
        return 'ETI'
    else:  # enrollment > 2500
        return 'GE'
source_entreprise['type_ent'] = source_entreprise['enrollment'].apply(determine_type_ent)

# Convertir la colonne "creation_date" en type datetime / Extraire l'année et créer une nouvelle colonn
source_entreprise['creation_date'] = pd.to_datetime(source_entreprise['creation_date'])
source_entreprise['creation_year'] = source_entreprise['creation_date'].dt.year

# Supprimer la seconde colonne 'ape_code' dupliquée
source_entreprise = source_entreprise.loc[:, ~source_entreprise.columns.duplicated()]

# ratio moyen 2018-2022
source_entreprise['resultat_exploitation_ratio'] = source_entreprise[['resultat_exploitation_ratio_2021', 'resultat_exploitation_ratio_2020', 'resultat_exploitation_ratio_2019', 'resultat_exploitation_ratio_2018']].mean(axis=1)
source_entreprise['net_result'] = source_entreprise[['net_result_2021', 'net_result_2020', 'net_result_2019', 'net_result_2018']].mean(axis=1)
source_entreprise['current_assets'] = source_entreprise[['current_assets_2021', 'current_assets_2020', 'current_assets_2019', 'current_assets_2018']].mean(axis=1)
source_entreprise['equity'] = source_entreprise[['equity_2021', 'equity_2020', 'equity_2019', 'equity_2018']].mean(axis=1)
source_entreprise['current_liabilities'] = source_entreprise[['current_liabilities_2021', 'current_liabilities_2020', 'current_liabilities_2019', 'current_liabilities_2018']].mean(axis=1)
source_entreprise['revenue'] = source_entreprise[['revenue_2018', 'revenue_2019', 'revenue_2020', 'revenue_2021', 'revenue_2022']].mean(axis=1)
source_entreprise['robustness_ratio'] = source_entreprise[['robustness_ratio_2018', 'robustness_ratio_2019', 'robustness_ratio_2020', 'robustness_ratio_2021', 'robustness_ratio_2022']].mean(axis=1)
source_entreprise['solvability_ratio'] = source_entreprise[['solvability_ratio_2018', 'solvability_ratio_2019', 'solvability_ratio_2020', 'solvability_ratio_2021', 'solvability_ratio_2022']].mean(axis=1)
source_entreprise['net_debt'] = source_entreprise[['net_debt_2018', 'net_debt_2019', 'net_debt_2020', 'net_debt_2021', 'net_debt_2022']].mean(axis=1)
source_entreprise['gross_operating_ebitda'] = source_entreprise[['gross_operating_ebitda_2021', 'gross_operating_ebitda_2020', 'gross_operating_ebitda_2019', 'gross_operating_ebitda_2018']].mean(axis=1)
source_entreprise['gross_operating_ebitda_ratio'] = source_entreprise[['gross_operating_ebitda_ratio_2021', 'gross_operating_ebitda_ratio_2020', 'gross_operating_ebitda_ratio_2019', 'gross_operating_ebitda_ratio_2018']].mean(axis=1)
source_entreprise['CAGR_18_22'] = source_entreprise[['growth_ratio_2021', 'growth_ratio_2020', 'growth_ratio_2019']].mean(axis=1)

#hypothese taux interet de la dette à 3% / taux de rendement des actionnaires à 8%
source_entreprise['RCI_2018']=source_entreprise['net_result_2018']/(source_entreprise['current_assets_2018']-source_entreprise['current_liabilities_2018'])
source_entreprise['RCI_2019']=source_entreprise['net_result_2019']/(source_entreprise['current_assets_2019']-source_entreprise['current_liabilities_2019'])
source_entreprise['RCI_2020']=source_entreprise['net_result_2020']/(source_entreprise['current_assets_2020']-source_entreprise['current_liabilities_2020'])
source_entreprise['RCI_2021']=source_entreprise['net_result_2021']/(source_entreprise['current_assets_2021']-source_entreprise['current_liabilities_2021'])
source_entreprise['RCI_2022']=source_entreprise['net_result_2022']/(source_entreprise['current_assets_2022']-source_entreprise['current_liabilities_2022'])
source_entreprise['RCI']=source_entreprise['net_result']/(source_entreprise['current_assets']-source_entreprise['current_liabilities'])
source_entreprise['total_fonds']=source_entreprise['equity']+source_entreprise['net_debt']
source_entreprise['equity_costs']=(source_entreprise['equity']/source_entreprise['total_fonds']*0.08)+(source_entreprise['net_debt']/source_entreprise['total_fonds']*0.03)
source_entreprise['taux de recrutement']=(source_entreprise['indeed_job_results_count']/source_entreprise['enrollment'])
source_entreprise['RdtCpx_2018']=source_entreprise['net_result_2018']/(source_entreprise['equity_2018'])
source_entreprise['RdtCpx_2019']=source_entreprise['net_result_2019']/(source_entreprise['equity_2019'])
source_entreprise['RdtCpx_2020']=source_entreprise['net_result_2020']/(source_entreprise['equity_2020'])
source_entreprise['RdtCpx_2021']=source_entreprise['net_result_2021']/(source_entreprise['equity_2021'])
source_entreprise['RdtCpx_2022']=source_entreprise['net_result_2022']/(source_entreprise['equity_2022'])
source_entreprise['RdtCpx']=source_entreprise['net_result']/(source_entreprise['equity'])
source_entreprise['FRN_2018']=source_entreprise['current_assets_2018']-(source_entreprise['current_liabilities_2018'])
source_entreprise['FRN_2019']=source_entreprise['current_assets_2019']-(source_entreprise['current_liabilities_2019'])
source_entreprise['FRN_2020']=source_entreprise['current_assets_2020']-(source_entreprise['current_liabilities_2020'])
source_entreprise['FRN_2021']=source_entreprise['current_assets_2021']-(source_entreprise['current_liabilities_2021'])
source_entreprise['FRN_2022']=source_entreprise['current_assets_2022']-(source_entreprise['current_liabilities_2022'])
source_entreprise['FRN']=source_entreprise['current_assets']-(source_entreprise['current_liabilities'])
source_entreprise['reimbursement_ratio_2018']=source_entreprise['net_debt_2018']/(source_entreprise['equity_2018'])
source_entreprise['reimbursement_ratio_2019']=source_entreprise['net_debt_2019']/(source_entreprise['equity_2019'])
source_entreprise['reimbursement_ratio_2020']=source_entreprise['net_debt_2020']/(source_entreprise['equity_2020'])
source_entreprise['reimbursement_ratio_2021']=source_entreprise['net_debt_2021']/(source_entreprise['equity_2021'])
source_entreprise['reimbursement_ratio_2022']=source_entreprise['net_debt_2022']/(source_entreprise['equity_2022'])
source_entreprise['reimbursement_ratio']=source_entreprise['current_liabilities']/(source_entreprise['equity'])

In [156]:
# Définir la valeur seuil
valeur_plafond = 1000000000  # 10 millions

# Créer un nouveau DataFrame avec les lignes où la colonne 'revenue' est inférieur au plafond
nouveau_source_entreprise = source_entreprise[source_entreprise['revenue'] < valeur_plafond]

# decrit la moyenne des revenues en arrondissant à deux chiffres après la virgule
(nouveau_source_entreprise['revenue'].describe() / 1e6).round(2)

count      0.01
mean      45.17
std      107.23
min        0.00
25%        5.74
50%       12.02
75%       33.01
max      996.36
Name: revenue, dtype: float64

In [157]:
colonnes = list(nouveau_source_entreprise.columns)
for colonne in colonnes:
    print(colonne)

estimated_revenue_estimated_revenue_2020
instagram_url
ape_code
indeed_about_content
banking_data_solde_credit_equipement
net_result_2018
cartography_liens_entreprises_personnes
derniere_mise_a_jour_rcs
banking_data_bdf_score
revenue_2020
additional_info_naf_code
estimated_revenue_average_growth_of_the_siren
revenue_2022
solvability_ratio_2019
corporate_officer_name
estimated_revenue_estimated_revenue_2021
estimated_revenue_estimated_growth_2023
gross_operating_ebitda_ratio_2018
company_name
ape_name
banking_data_insurance_locaux
current_liabilities_2020
banking_data_is_significantly_changing
cartography_error
banking_data_solde_courant_moyen
beneficiaires_effectifs
banking_data_insurance_vehicules_pro
marques
equity_2021
resultat_exploitation_ratio_2022
opportunities_of_the_siret
gross_operating_ebitda_2020
web_scrap
postal_address_postal_address_additional_name
strenghts_of_the_siret
current_liabilities_2018
last_number_of_employees
gross_operating_ebitda_ratio_2019
google_search_keyword
linkedin_posts
cartography_liens_entreprises_entreprises
enrollment
corporate_object
solvability_ratio_2020
net_result_2020
equity_2022
current_assets_2022
gross_operating_ebitda_ratio_2021
bodacc_important_message
postal_address_street
current_liabilities_2019
gross_operating_ebitda_ratio_2022
banking_data_flux_3m
reimbursement_ratio_2018
corporate_officer_birth_date
legal_company_form
net_result_2022
last_bodacc
employees_number_for_linkedin
net_result_2021
linkedin_jobs
postal_address_lat
solvability_ratio_2018
google_search_description
estimated_revenue_segment_of_the_siren
banking_data_denomination
company_name_index
estimated_revenue_estimated_revenue_2019
range_employee_for_linkedin
glassdoor_avis
banking_data_flux_1m
gross_operating_ebitda_2021
current_liabilities_2022
web_site_url
twitter_url
web_infos_synthesis
cartography_message
additional_info_region
web_infos_narrative
equity_2018
logo
estimated_revenue_estimated_revenue_2022
cartography_entreprises
growth_ratio_2021
resultat_exploitation_ratio_2019
capital
resultat_exploitation_ratio_2020
roe_2022
net_debt_2021
current_assets_2020
corporate_officer_role
revenue_2021
growth_ratio_2020
resultat_d_exploitation_2019
indeed_job_results_count
google_business_notation
additional_info_region_code
weaknesses_of_the_siret
banking_data_atradius_score
banking_data_flux_1y
google_business_nb_avis
robustness_ratio_2018
current_assets_2019
net_debt_2020
web_infos_news_positiveness
net_debt_2022
banking_data_flux_6m
reimbursement_ratio_2022
equity_2019
estimated_revenue_siren
banking_data_solde_placement
roe_2021
cartography_personnes
banking_data_insurance_sinistres
roe_2019
robustness_ratio_2021
growth_ratio_2019
current_assets_2018
net_debt_2018
cartography_statusCode
siren
commercial_name
current_assets_2021
google_business_resultats
robustness_ratio_2020
facebook_url
siret
representants
robustness_ratio_2022
revenue_2019
gross_operating_ebitda_2018
gross_operating_ebitda_2019
current_liabilities_2021
resultat_exploitation_ratio_2018
net_debt_2019
estimated_revenue_average_ebe_of_the_siren
banking_data_insurance_lies_a_activite
estimated_revenue_estimated_revenue_2023
publications_bodacc
postal_address_city
postal_address_postal_code
net_result_2019
resultat_d_exploitation_2021
glassdoor_notation
societeinfo_growth_ratio_2022
reimbursement_ratio_2020
roe_2018
banking_data_is_multi_bank
gross_operating_ebitda_2022
vat_number
creation_date
indeed_job_results
equity_2020
reimbursement_ratio_2019
revenue_2018
region_index
postal_address_lng
solvability_ratio_2021
pfs_id
banking_data_insurance_salaries
postal_address_country
resultat_exploitation_ratio_2021
postal_address_country_code
derniere_mise_a_jour_sirene
reimbursement_ratio_2021
banking_data_siren
resultat_d_exploitation_2022
resultat_d_exploitation_2020
solvability_ratio_2022
roe_2020
banking_data_siret
resultat_d_exploitation_2018
threats_of_the_siret
gross_operating_ebitda_ratio_2020
greffe_name
robustness_ratio_2019
procedures_collectives
type_ent
creation_year
resultat_exploitation_ratio
net_result
current_assets
equity
current_liabilities
revenue
robustness_ratio
solvability_ratio
net_debt
gross_operating_ebitda
gross_operating_ebitda_ratio
CAGR_18_22
RCI_2018
RCI_2019
RCI_2020
RCI_2021
RCI_2022
RCI
total_fonds
equity_costs
taux de recrutement
RdtCpx_2018
RdtCpx_2019
RdtCpx_2020
RdtCpx_2021
RdtCpx_2022
RdtCpx
FRN_2018
FRN_2019
FRN_2020
FRN_2021
FRN_2022
FRN
reimbursement_ratio

In [158]:
nouveau_source_entreprise.shape

(9993, 213)

In [159]:
nouveau_source_entreprise = nouveau_source_entreprise.copy()
# Remplacer inf et -inf par NaN
nouveau_source_entreprise['RCI'].replace([np.inf, -np.inf], np.nan, inplace=True)

# Calcul de la moyenne et de l'écart-type
moyenne = nouveau_source_entreprise['RCI'].mean()
ecart_type = nouveau_source_entreprise['RCI'].std()

# Calcul du seuil supérieur / inférieur
seuil_sup = moyenne + 1.5 * ecart_type
seuil_inf = moyenne - 1.5 * ecart_type
# Filtrage des valeurs qui dépassent le seuil supérieur
nouveau_source_entreprise['RCI'] = nouveau_source_entreprise['RCI'].clip(lower=seuil_inf, upper=seuil_sup)

nouveau_source_entreprise['RCI'].describe()

count    8830.000000
mean        0.156088
std         4.295936
min       -83.068499
25%        -0.024593
50%         0.052612
75%         0.190931
max        85.134563
Name: RCI, dtype: float64

In [160]:
# Vérifier s'il y a des valeurs NaN dans la colonne 
if nouveau_source_entreprise['RCI'].isnull().any():
    nb_nan = nouveau_source_entreprise['RCI'].isnull().sum()
    print("Il y a des valeurs NaN dans la colonne 'RCI: '",nb_nan )
    nouveau_source_entreprise['RCI'] = nouveau_source_entreprise['RCI'].fillna(nouveau_source_entreprise['societeinfo_growth_ratio_2022'])
    nb_nan = nouveau_source_entreprise['RCI'].isnull().sum()
    print("Il y a encore des valeurs NaN dans la colonne 'RCI: '",nb_nan )
    # Supprimer les lignes avec des valeurs NaN dans la colonne 'B'
    nouveau_source_entreprise = nouveau_source_entreprise.dropna(subset=['RCI'])
    nb_nan = nouveau_source_entreprise['RCI'].isnull().sum()
    print("Il y a encore des valeurs NaN dans la colonne 'RCI après purge: '",nb_nan )
else:
    print("Il n'y a pas de valeurs NaN dans la colonne 'RCI'")

Il y a des valeurs NaN dans la colonne 'RCI: ' 1163
Il y a encore des valeurs NaN dans la colonne 'RCI: ' 900
Il y a encore des valeurs NaN dans la colonne 'RCI après purge: ' 0

In [161]:
nouveau_source_entreprise = nouveau_source_entreprise.copy()
# Remplacer inf et -inf par NaN
nouveau_source_entreprise['CAGR_18_22'].replace([np.inf, -np.inf], np.nan, inplace=True)
# Calcul de la moyenne et de l'écart-type
moyenne = nouveau_source_entreprise['CAGR_18_22'].mean()
ecart_type = nouveau_source_entreprise['CAGR_18_22'].std()

# Calcul du seuil supérieur / inférieur
seuil_sup = 2
seuil_inf = -1
# Filtrage des valeurs qui dépassent le seuil supérieur
nouveau_source_entreprise['CAGR_18_22'] = nouveau_source_entreprise['CAGR_18_22'].clip(lower=seuil_inf, upper=seuil_sup)

nouveau_source_entreprise['CAGR_18_22'].describe()

count    8642.000000
mean        0.137007
std         0.376038
min        -0.885083
25%        -0.008549
50%         0.044956
75%         0.134849
max         2.000000
Name: CAGR_18_22, dtype: float64

In [162]:
# Vérifier s'il y a des valeurs NaN dans la colonne 
if nouveau_source_entreprise['CAGR_18_22'].isnull().any():
    nb_nan = nouveau_source_entreprise['CAGR_18_22'].isnull().sum()
    print("Il y a des valeurs NaN dans la colonne 'CAGR_18_22: '",nb_nan )
    nouveau_source_entreprise['CAGR_18_22'] = nouveau_source_entreprise['CAGR_18_22'].fillna(nouveau_source_entreprise['RCI_2022'])
    nb_nan = nouveau_source_entreprise['CAGR_18_22'].isnull().sum()
    print("Il y a encore des valeurs NaN dans la colonne 'CAGR_18_22: '",nb_nan )
    # Supprimer les lignes avec des valeurs NaN dans la colonne 'B'
    nouveau_source_entreprise = nouveau_source_entreprise.dropna(subset=['CAGR_18_22'])
    nb_nan = nouveau_source_entreprise['CAGR_18_22'].isnull().sum()
    print("Il y a encore des valeurs NaN dans la colonne 'CAGR_18_22 après purge: '",nb_nan )
else:
    print("Il n'y a pas de valeurs NaN dans la colonne 'CAGR_18_22'")

Il y a des valeurs NaN dans la colonne 'CAGR_18_22: ' 451
Il y a encore des valeurs NaN dans la colonne 'CAGR_18_22: ' 395
Il y a encore des valeurs NaN dans la colonne 'CAGR_18_22 après purge: ' 0

In [163]:
nouveau_source_entreprise = nouveau_source_entreprise.copy()
# Remplacer inf et -inf par NaN
nouveau_source_entreprise['RdtCpx'].replace([np.inf, -np.inf], np.nan, inplace=True)

# Calcul de la moyenne et de l'écart-type
moyenne = nouveau_source_entreprise['RdtCpx'].mean()
ecart_type = nouveau_source_entreprise['RdtCpx'].std()

# Calcul du seuil supérieur / inférieur
seuil_sup = moyenne + 0.3 * ecart_type
seuil_inf = moyenne - 0.3 * ecart_type
# Filtrage des valeurs qui dépassent le seuil supérieur
nouveau_source_entreprise['RdtCpx'] = nouveau_source_entreprise['RdtCpx'].clip(lower=seuil_inf, upper=seuil_sup)

nouveau_source_entreprise['RdtCpx'].describe()

count    8400.000000
mean        0.200019
std         1.862444
min       -27.218450
25%         0.045058
50%         0.143610
75%         0.308062
max        29.648421
Name: RdtCpx, dtype: float64

In [164]:
# Vérifier s'il y a des valeurs NaN dans la colonne 
if nouveau_source_entreprise['RdtCpx'].isnull().any():
    nb_nan = nouveau_source_entreprise['RdtCpx'].isnull().sum()
    print("Il y a des valeurs NaN dans la colonne 'RdtCpx: '",nb_nan )
    nouveau_source_entreprise['RdtCpx'] = nouveau_source_entreprise['RdtCpx'].fillna(nouveau_source_entreprise['RdtCpx_2022'])
    nb_nan = nouveau_source_entreprise['RdtCpx'].isnull().sum()
    print("Il y a encore des valeurs NaN dans la colonne 'RdtCpx: '",nb_nan )
    # Supprimer les lignes avec des valeurs NaN dans la colonne 'B'
    nouveau_source_entreprise = nouveau_source_entreprise.dropna(subset=['RdtCpx'])
    nb_nan = nouveau_source_entreprise['RdtCpx'].isnull().sum()
    print("Il y a encore des valeurs NaN dans la colonne 'RdtCpx après purge: '",nb_nan )
else:
    print("Il n'y a pas de valeurs NaN dans la colonne 'RdtCpx'")

Il y a des valeurs NaN dans la colonne 'RdtCpx: ' 298
Il y a encore des valeurs NaN dans la colonne 'RdtCpx: ' 136
Il y a encore des valeurs NaN dans la colonne 'RdtCpx après purge: ' 0

In [165]:
nouveau_source_entreprise = nouveau_source_entreprise.copy()
# Remplacer inf et -inf par NaN
nouveau_source_entreprise['solvability_ratio'].replace([np.inf, -np.inf], np.nan, inplace=True)

# Calcul de la moyenne et de l'écart-type
moyenne = nouveau_source_entreprise['solvability_ratio'].mean()
ecart_type = nouveau_source_entreprise['solvability_ratio'].std()

# Calcul du seuil supérieur / inférieur
seuil_sup = 10
seuil_inf = -10
# Filtrage des valeurs qui dépassent le seuil supérieur
nouveau_source_entreprise['solvability_ratio'] = nouveau_source_entreprise['solvability_ratio'].clip(lower=seuil_inf, upper=seuil_sup)

nouveau_source_entreprise['solvability_ratio'].describe()

count    8504.000000
mean        2.519731
std         3.401011
min       -10.000000
25%         1.058672
50%         1.943570
75%         3.648644
max        10.000000
Name: solvability_ratio, dtype: float64

In [166]:
# Vérifier s'il y a des valeurs NaN dans la colonne 
if nouveau_source_entreprise['solvability_ratio'].isnull().any():
    nb_nan = nouveau_source_entreprise['solvability_ratio'].isnull().sum()
    print("Il y a des valeurs NaN dans la colonne 'solvability_ratio: '",nb_nan )
    nouveau_source_entreprise['solvability_ratio'] = nouveau_source_entreprise['solvability_ratio'].fillna(nouveau_source_entreprise['solvability_ratio_2022'])
    nb_nan = nouveau_source_entreprise['solvability_ratio'].isnull().sum()
    print("Il y a encore des valeurs NaN dans la colonne 'solvability_ratio: '",nb_nan )
    # Supprimer les lignes avec des valeurs NaN dans la colonne 'B'
    nouveau_source_entreprise = nouveau_source_entreprise.dropna(subset=['solvability_ratio'])
    nb_nan = nouveau_source_entreprise['solvability_ratio'].isnull().sum()
    print("Il y a encore des valeurs NaN dans la colonne 'Rsolvability_ratio après purge: '",nb_nan )
else:
    print("Il n'y a pas de valeurs NaN dans la colonne 'solvability_ratio'")

Il y a des valeurs NaN dans la colonne 'solvability_ratio: ' 58
Il y a encore des valeurs NaN dans la colonne 'solvability_ratio: ' 58
Il y a encore des valeurs NaN dans la colonne 'Rsolvability_ratio après purge: ' 0

In [167]:
nouveau_source_entreprise = nouveau_source_entreprise.copy()
# Remplacer inf et -inf par NaN
nouveau_source_entreprise['reimbursement_ratio'].replace([np.inf, -np.inf], np.nan, inplace=True)

# Calcul de la moyenne et de l'écart-type
moyenne = nouveau_source_entreprise['reimbursement_ratio'].mean()
ecart_type = nouveau_source_entreprise['reimbursement_ratio'].std()

# Calcul du seuil supérieur / inférieur
seuil_sup = 10
seuil_inf = -10
# Filtrage des valeurs qui dépassent le seuil supérieur
nouveau_source_entreprise['reimbursement_ratio'] = nouveau_source_entreprise['reimbursement_ratio'].clip(lower=seuil_inf, upper=seuil_sup)

nouveau_source_entreprise['reimbursement_ratio'].describe()

count    8345.000000
mean        1.078917
std         1.009887
min       -10.000000
25%         1.000000
50%         1.010421
75%         1.079462
max        10.000000
Name: reimbursement_ratio, dtype: float64

In [168]:
# Vérifier s'il y a des valeurs NaN dans la colonne 
if nouveau_source_entreprise['reimbursement_ratio'].isnull().any():
    nb_nan = nouveau_source_entreprise['reimbursement_ratio'].isnull().sum()
    print("Il y a des valeurs NaN dans la colonne 'reimbursement_ratio: '",nb_nan )
    nouveau_source_entreprise['reimbursement_ratio'] = nouveau_source_entreprise['reimbursement_ratio'].fillna(nouveau_source_entreprise['reimbursement_ratio_2022'])
    nb_nan = nouveau_source_entreprise['reimbursement_ratio'].isnull().sum()
    print("Il y a encore des valeurs NaN dans la colonne 'reimbursement_ratio: '",nb_nan )
    # Supprimer les lignes avec des valeurs NaN dans la colonne 'B'
    nouveau_source_entreprise = nouveau_source_entreprise.dropna(subset=['reimbursement_ratio'])
    nb_nan = nouveau_source_entreprise['reimbursement_ratio'].isnull().sum()
    print("Il y a encore des valeurs NaN dans la colonne 'reimbursementy_ratio après purge: '",nb_nan )
else:
    print("Il n'y a pas de valeurs NaN dans la colonne 'reimbursement_ratio'")

Il y a des valeurs NaN dans la colonne 'reimbursement_ratio: ' 159
Il y a encore des valeurs NaN dans la colonne 'reimbursement_ratio: ' 0
Il y a encore des valeurs NaN dans la colonne 'reimbursementy_ratio après purge: ' 0

In [169]:
nouveau_source_entreprise = nouveau_source_entreprise.copy()
# Remplacer inf et -inf par NaN
nouveau_source_entreprise['robustness_ratio'].replace([np.inf, -np.inf], np.nan, inplace=True)

# Calcul de la moyenne et de l'écart-type
moyenne = nouveau_source_entreprise['robustness_ratio'].mean()
ecart_type = nouveau_source_entreprise['robustness_ratio'].std()

# Calcul du seuil supérieur / inférieur
seuil_sup = 10
seuil_inf = -10
# Filtrage des valeurs qui dépassent le seuil supérieur
nouveau_source_entreprise['robustness_ratio'] = nouveau_source_entreprise['robustness_ratio'].clip(lower=seuil_inf, upper=seuil_sup)

nouveau_source_entreprise['robustness_ratio'].describe()

count    8500.000000
mean        0.028547
std         0.702829
min       -10.000000
25%         0.001295
50%         0.017344
75%         0.045278
max        10.000000
Name: robustness_ratio, dtype: float64

In [170]:
# Vérifier s'il y a des valeurs NaN dans la colonne 
if nouveau_source_entreprise['robustness_ratio'].isnull().any():
    nb_nan = nouveau_source_entreprise['robustness_ratio'].isnull().sum()
    print("Il y a des valeurs NaN dans la colonne 'robustness_ratio: '",nb_nan )
    nouveau_source_entreprise['robustness_ratio'] = nouveau_source_entreprise['robustness_ratio'].fillna(nouveau_source_entreprise['robustness_ratio_2022'])
    nb_nan = nouveau_source_entreprise['robustness_ratio'].isnull().sum()
    print("Il y a encore des valeurs NaN dans la colonne 'robustness_ratio: '",nb_nan )
    # Supprimer les lignes avec des valeurs NaN dans la colonne 'B'
    nouveau_source_entreprise = nouveau_source_entreprise.dropna(subset=['robustness_ratio'])
    nb_nan = nouveau_source_entreprise['robustness_ratio'].isnull().sum()
    print("Il y a encore des valeurs NaN dans la colonne 'robustness_ratio après purge: '",nb_nan )
else:
    print("Il n'y a pas de valeurs NaN dans la colonne 'robustness_ratio'")

Il y a des valeurs NaN dans la colonne 'robustness_ratio: ' 4
Il y a encore des valeurs NaN dans la colonne 'robustness_ratio: ' 4
Il y a encore des valeurs NaN dans la colonne 'robustness_ratio après purge: ' 0

In [171]:
# nombre d entreprise par annee de creation
ent_par_an=nouveau_source_entreprise.groupby('creation_year').count()
ent_par_an.head(5)

,estimated_revenue_estimated_revenue_2020,instagram_url,ape_code,indeed_about_content,banking_data_solde_credit_equipement,net_result_2018,cartography_liens_entreprises_personnes,derniere_mise_a_jour_rcs,banking_data_bdf_score,revenue_2020,...,RdtCpx_2021,RdtCpx_2022,RdtCpx,FRN_2018,FRN_2019,FRN_2020,FRN_2021,FRN_2022,FRN,reimbursement_ratio
creation_year,,,,,,,,,,,,,,,,,,,,,
1900.0,3,2,3,1,1,3,3,0,1,3,...,3,0,3,3,3,3,3,0,3,3
1901.0,13,9,13,0,0,13,13,4,0,13,...,12,3,13,13,13,13,12,3,13,13
1909.0,1,0,1,0,0,1,1,0,0,1,...,1,0,1,1,1,1,1,0,1,1
1910.0,1,1,1,0,0,1,1,1,0,1,...,0,0,1,1,1,1,0,0,1,1
1912.0,1,1,1,0,0,1,1,1,0,1,...,1,0,1,1,1,1,1,0,1,1

In [172]:
# decrit la moyenne des revenues en arrondissant à deux chiffres après la virgule
(nouveau_source_entreprise['revenue'].describe() / 1e6).round(2)

count      0.01
mean      51.34
std      113.57
min        0.02
25%        7.26
50%       14.67
75%       39.05
max      996.36
Name: revenue, dtype: float64

In [173]:
# Grouper par 'ape_code' et compter les occurrences
ent_par_ape = nouveau_source_entreprise.groupby('ape_code').count()

# Afficher les 5 premières lignes du DataFrame résultant
ent_par_ape.head(5)

,estimated_revenue_estimated_revenue_2020,instagram_url,indeed_about_content,banking_data_solde_credit_equipement,net_result_2018,cartography_liens_entreprises_personnes,derniere_mise_a_jour_rcs,banking_data_bdf_score,revenue_2020,additional_info_naf_code,...,RdtCpx_2021,RdtCpx_2022,RdtCpx,FRN_2018,FRN_2019,FRN_2020,FRN_2021,FRN_2022,FRN,reimbursement_ratio
ape_code,,,,,,,,,,,,,,,,,,,,,
0240Z,1,1,0,0,1,1,0,0,1,1,...,1,0,1,1,1,1,1,0,1,1
0311Z,1,1,0,0,0,1,0,0,1,1,...,1,0,1,0,1,1,1,0,1,1
0812Z,3,2,0,0,3,3,1,0,3,3,...,3,1,3,3,3,3,3,1,3,3
0893Z,1,0,0,0,1,1,1,0,1,1,...,1,1,1,1,1,1,1,1,1,1
1011Z,4,2,0,0,4,4,1,0,4,4,...,3,1,4,4,3,4,4,1,4,4

In [174]:
# Créer une nouvelle colonne 
nombre_ent_series = ent_par_ape['siren']

# Concaténer la colonne existante avec la nouvelle colonne dans une seule opération
ent_par_ape = pd.concat([ent_par_ape, nombre_ent_series.rename('nombre_ent')], axis=1)

In [175]:
colonnes = list(nouveau_source_entreprise.columns)
for colonne in colonnes:
    print(colonne)

estimated_revenue_estimated_revenue_2020
instagram_url
ape_code
indeed_about_content
banking_data_solde_credit_equipement
net_result_2018
cartography_liens_entreprises_personnes
derniere_mise_a_jour_rcs
banking_data_bdf_score
revenue_2020
additional_info_naf_code
estimated_revenue_average_growth_of_the_siren
revenue_2022
solvability_ratio_2019
corporate_officer_name
estimated_revenue_estimated_revenue_2021
estimated_revenue_estimated_growth_2023
gross_operating_ebitda_ratio_2018
company_name
ape_name
banking_data_insurance_locaux
current_liabilities_2020
banking_data_is_significantly_changing
cartography_error
banking_data_solde_courant_moyen
beneficiaires_effectifs
banking_data_insurance_vehicules_pro
marques
equity_2021
resultat_exploitation_ratio_2022
opportunities_of_the_siret
gross_operating_ebitda_2020
web_scrap
postal_address_postal_address_additional_name
strenghts_of_the_siret
current_liabilities_2018
last_number_of_employees
gross_operating_ebitda_ratio_2019
google_search_keyword
linkedin_posts
cartography_liens_entreprises_entreprises
enrollment
corporate_object
solvability_ratio_2020
net_result_2020
equity_2022
current_assets_2022
gross_operating_ebitda_ratio_2021
bodacc_important_message
postal_address_street
current_liabilities_2019
gross_operating_ebitda_ratio_2022
banking_data_flux_3m
reimbursement_ratio_2018
corporate_officer_birth_date
legal_company_form
net_result_2022
last_bodacc
employees_number_for_linkedin
net_result_2021
linkedin_jobs
postal_address_lat
solvability_ratio_2018
google_search_description
estimated_revenue_segment_of_the_siren
banking_data_denomination
company_name_index
estimated_revenue_estimated_revenue_2019
range_employee_for_linkedin
glassdoor_avis
banking_data_flux_1m
gross_operating_ebitda_2021
current_liabilities_2022
web_site_url
twitter_url
web_infos_synthesis
cartography_message
additional_info_region
web_infos_narrative
equity_2018
logo
estimated_revenue_estimated_revenue_2022
cartography_entreprises
growth_ratio_2021
resultat_exploitation_ratio_2019
capital
resultat_exploitation_ratio_2020
roe_2022
net_debt_2021
current_assets_2020
corporate_officer_role
revenue_2021
growth_ratio_2020
resultat_d_exploitation_2019
indeed_job_results_count
google_business_notation
additional_info_region_code
weaknesses_of_the_siret
banking_data_atradius_score
banking_data_flux_1y
google_business_nb_avis
robustness_ratio_2018
current_assets_2019
net_debt_2020
web_infos_news_positiveness
net_debt_2022
banking_data_flux_6m
reimbursement_ratio_2022
equity_2019
estimated_revenue_siren
banking_data_solde_placement
roe_2021
cartography_personnes
banking_data_insurance_sinistres
roe_2019
robustness_ratio_2021
growth_ratio_2019
current_assets_2018
net_debt_2018
cartography_statusCode
siren
commercial_name
current_assets_2021
google_business_resultats
robustness_ratio_2020
facebook_url
siret
representants
robustness_ratio_2022
revenue_2019
gross_operating_ebitda_2018
gross_operating_ebitda_2019
current_liabilities_2021
resultat_exploitation_ratio_2018
net_debt_2019
estimated_revenue_average_ebe_of_the_siren
banking_data_insurance_lies_a_activite
estimated_revenue_estimated_revenue_2023
publications_bodacc
postal_address_city
postal_address_postal_code
net_result_2019
resultat_d_exploitation_2021
glassdoor_notation
societeinfo_growth_ratio_2022
reimbursement_ratio_2020
roe_2018
banking_data_is_multi_bank
gross_operating_ebitda_2022
vat_number
creation_date
indeed_job_results
equity_2020
reimbursement_ratio_2019
revenue_2018
region_index
postal_address_lng
solvability_ratio_2021
pfs_id
banking_data_insurance_salaries
postal_address_country
resultat_exploitation_ratio_2021
postal_address_country_code
derniere_mise_a_jour_sirene
reimbursement_ratio_2021
banking_data_siren
resultat_d_exploitation_2022
resultat_d_exploitation_2020
solvability_ratio_2022
roe_2020
banking_data_siret
resultat_d_exploitation_2018
threats_of_the_siret
gross_operating_ebitda_ratio_2020
greffe_name
robustness_ratio_2019
procedures_collectives
type_ent
creation_year
resultat_exploitation_ratio
net_result
current_assets
equity
current_liabilities
revenue
robustness_ratio
solvability_ratio
net_debt
gross_operating_ebitda
gross_operating_ebitda_ratio
CAGR_18_22
RCI_2018
RCI_2019
RCI_2020
RCI_2021
RCI_2022
RCI
total_fonds
equity_costs
taux de recrutement
RdtCpx_2018
RdtCpx_2019
RdtCpx_2020
RdtCpx_2021
RdtCpx_2022
RdtCpx
FRN_2018
FRN_2019
FRN_2020
FRN_2021
FRN_2022
FRN
reimbursement_ratio

In [183]:
liste_colonnes = ['ape_code','siren','siret','capital','enrollment','last_number_of_employees','employees_number_for_linkedin','revenue_2021',
                  'revenue_2020','revenue_2019','revenue_2018','net_result_2021','equity_2021','roe_2021','net_debt_2021',
                  'current_assets_2021','current_liabilities_2021','solvability_ratio_2021','gross_operating_ebitda_2021',
                  'gross_operating_ebitda_ratio_2021','reimbursement_ratio_2021','robustness_ratio_2021','net_result_2020',
                  'equity_2020','roe_2020','net_debt_2020','current_assets_2020','current_liabilities_2020',
                  'solvability_ratio_2020','gross_operating_ebitda_2020','gross_operating_ebitda_ratio_2020',
                  'reimbursement_ratio_2020','robustness_ratio_2020','net_result_2019','equity_2019','roe_2019',
                  'net_debt_2019','current_assets_2019','current_liabilities_2019','solvability_ratio_2019',
                  'gross_operating_ebitda_2019','gross_operating_ebitda_ratio_2019','reimbursement_ratio_2019',
                  'robustness_ratio_2019','net_result_2018','equity_2018','roe_2018','net_debt_2018','current_assets_2018',
                  'current_liabilities_2018','solvability_ratio_2018','gross_operating_ebitda_2018',
                  'gross_operating_ebitda_ratio_2018','reimbursement_ratio_2018','robustness_ratio_2018',
                  'growth_ratio_2021','growth_ratio_2020','growth_ratio_2019','societeinfo_growth_ratio_2022','resultat_exploitation_ratio_2021',
                  'resultat_exploitation_ratio_2020','resultat_exploitation_ratio_2019','resultat_exploitation_ratio_2018',
                  'revenue_2022','net_result_2022','equity_2022','roe_2022','net_debt_2022','current_assets_2022',
                  'current_liabilities_2022','solvability_ratio_2022','gross_operating_ebitda_2022',
                  'gross_operating_ebitda_ratio_2022','gross_operating_ebitda_ratio','reimbursement_ratio_2022',
                  'robustness_ratio_2022','resultat_exploitation_ratio_2022','resultat_d_exploitation_2021',
                  'resultat_d_exploitation_2020','resultat_d_exploitation_2019','resultat_d_exploitation_2018',
                  'resultat_d_exploitation_2022','resultat_exploitation_ratio','net_result','current_assets','equity',
                  'current_liabilities','revenue','reimbursement_ratio','robustness_ratio','solvability_ratio','net_debt',
                  'gross_operating_ebitda','CAGR_18_22','RCI_2018','RCI_2019','RCI_2020','RCI_2021','RCI_2022','RCI',
                  'total_fonds','equity_costs','RdtCpx','RdtCpx_2018','RdtCpx_2019','RdtCpx_2020','RdtCpx_2021','RdtCpx_2022']  

resultats = []  # Pour stocker les résultats après filtrage et calcul de la moyenne


# Remplacer les NaN par une chaîne de caractères vide dans tout le DataFrame
nouveau_source_entreprise = nouveau_source_entreprise[liste_colonnes].fillna(0)

In [185]:
# Itérer à travers chaque groupe

# retirer siren / siret / ape-code
liste_colonnes2 = ['capital','enrollment','last_number_of_employees','employees_number_for_linkedin','revenue_2021',
                  'revenue_2020','revenue_2019','revenue_2018','net_result_2021','equity_2021','roe_2021','net_debt_2021',
                  'current_assets_2021','current_liabilities_2021','solvability_ratio_2021','gross_operating_ebitda_2021',
                  'gross_operating_ebitda_ratio_2021','reimbursement_ratio_2021','robustness_ratio_2021','net_result_2020',
                  'equity_2020','roe_2020','net_debt_2020','current_assets_2020','current_liabilities_2020',
                  'solvability_ratio_2020','gross_operating_ebitda_2020','gross_operating_ebitda_ratio_2020',
                  'reimbursement_ratio_2020','robustness_ratio_2020','net_result_2019','equity_2019','roe_2019',
                  'net_debt_2019','current_assets_2019','current_liabilities_2019','solvability_ratio_2019',
                  'gross_operating_ebitda_2019','gross_operating_ebitda_ratio_2019','reimbursement_ratio_2019',
                  'robustness_ratio_2019','net_result_2018','equity_2018','roe_2018','net_debt_2018','current_assets_2018',
                  'current_liabilities_2018','solvability_ratio_2018','gross_operating_ebitda_2018',
                  'gross_operating_ebitda_ratio_2018','reimbursement_ratio_2018','robustness_ratio_2018',
                  'growth_ratio_2021','growth_ratio_2020','growth_ratio_2019','societeinfo_growth_ratio_2022','resultat_exploitation_ratio_2021',
                  'resultat_exploitation_ratio_2020','resultat_exploitation_ratio_2019','resultat_exploitation_ratio_2018',
                  'revenue_2022','net_result_2022','equity_2022','roe_2022','net_debt_2022','current_assets_2022',
                  'current_liabilities_2022','solvability_ratio_2022','gross_operating_ebitda_2022',
                  'gross_operating_ebitda_ratio_2022','gross_operating_ebitda_ratio','reimbursement_ratio_2022',
                  'robustness_ratio_2022','resultat_exploitation_ratio_2022','resultat_d_exploitation_2021',
                  'resultat_d_exploitation_2020','resultat_d_exploitation_2019','resultat_d_exploitation_2018',
                  'resultat_d_exploitation_2022','resultat_exploitation_ratio','net_result','current_assets','equity',
                  'current_liabilities','revenue','reimbursement_ratio','robustness_ratio','solvability_ratio','net_debt',
                  'gross_operating_ebitda','CAGR_18_22','RCI_2018','RCI_2019','RCI_2020','RCI_2021','RCI_2022','RCI',
                  'total_fonds','equity_costs','RdtCpx','RdtCpx_2018','RdtCpx_2019','RdtCpx_2020','RdtCpx_2021','RdtCpx_2022']


# Convertir les colonnes en numérique, en ignorant les erreurs pour celles qui ne peuvent pas être converties
for col in liste_colonnes2:
    nouveau_source_entreprise[col] = pd.to_numeric(nouveau_source_entreprise[col], errors='coerce')

for nom_groupe, groupe in nouveau_source_entreprise.groupby('ape_code'):
    Q1 = groupe[liste_colonnes2].quantile(0.25)
    Q3 = groupe[liste_colonnes2].quantile(0.75)
    IQR = Q3 - Q1
    
    # Filtrer les valeurs extrêmes dans le groupe
    filtre = ~((groupe[liste_colonnes2] < (Q1 - 1.5 * IQR)) | (groupe[liste_colonnes2] > (Q3 + 1.5 * IQR))).any(axis=1)
    donnees_filtrees = groupe[filtre]
    
    # Calculer la moyenne pour le groupe filtré et l'ajouter à la liste des résultats
    moyenne_groupe = donnees_filtrees[liste_colonnes2].mean()
    moyenne_groupe.name = nom_groupe  # Nommer la série de moyennes après le code du groupe
    resultats.append(moyenne_groupe)

# Combinez tous les résultats de groupe dans un nouveau DataFrame
moyennes_par_secteur = pd.DataFrame(resultats)

C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4575: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4575: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4575: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4575: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4575: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4575: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)

In [186]:
def renommer_colonnesmoy_selectionnees(dataframe, colonnes_a_renommer):
    # Créez un dictionnaire pour mapper les anciens noms aux nouveaux noms
    colonnes_renommees = {colonne: colonne + "_moy_sect" for colonne in colonnes_a_renommer}
    
    # Utilisez la méthode rename() pour renommer les colonnes sélectionnées du DataFrame
    dataframe.rename(columns=colonnes_renommees, inplace=True)
    
    return dataframe
colonnes_a_renommer=liste_colonnes
moyennes_par_secteur = renommer_colonnesmoy_selectionnees(moyennes_par_secteur, colonnes_a_renommer)

In [187]:
colonnes = list(moyennes_par_secteur.columns)
for colonne in colonnes:
    print(colonne)

capital_moy_sect
enrollment_moy_sect
last_number_of_employees_moy_sect
employees_number_for_linkedin_moy_sect
revenue_2021_moy_sect
revenue_2020_moy_sect
revenue_2019_moy_sect
revenue_2018_moy_sect
net_result_2021_moy_sect
equity_2021_moy_sect
roe_2021_moy_sect
net_debt_2021_moy_sect
current_assets_2021_moy_sect
current_liabilities_2021_moy_sect
solvability_ratio_2021_moy_sect
gross_operating_ebitda_2021_moy_sect
gross_operating_ebitda_ratio_2021_moy_sect
reimbursement_ratio_2021_moy_sect
robustness_ratio_2021_moy_sect
net_result_2020_moy_sect
equity_2020_moy_sect
roe_2020_moy_sect
net_debt_2020_moy_sect
current_assets_2020_moy_sect
current_liabilities_2020_moy_sect
solvability_ratio_2020_moy_sect
gross_operating_ebitda_2020_moy_sect
gross_operating_ebitda_ratio_2020_moy_sect
reimbursement_ratio_2020_moy_sect
robustness_ratio_2020_moy_sect
net_result_2019_moy_sect
equity_2019_moy_sect
roe_2019_moy_sect
net_debt_2019_moy_sect
current_assets_2019_moy_sect
current_liabilities_2019_moy_sect
solvability_ratio_2019_moy_sect
gross_operating_ebitda_2019_moy_sect
gross_operating_ebitda_ratio_2019_moy_sect
reimbursement_ratio_2019_moy_sect
robustness_ratio_2019_moy_sect
net_result_2018_moy_sect
equity_2018_moy_sect
roe_2018_moy_sect
net_debt_2018_moy_sect
current_assets_2018_moy_sect
current_liabilities_2018_moy_sect
solvability_ratio_2018_moy_sect
gross_operating_ebitda_2018_moy_sect
gross_operating_ebitda_ratio_2018_moy_sect
reimbursement_ratio_2018_moy_sect
robustness_ratio_2018_moy_sect
growth_ratio_2021_moy_sect
growth_ratio_2020_moy_sect
growth_ratio_2019_moy_sect
societeinfo_growth_ratio_2022_moy_sect
resultat_exploitation_ratio_2021_moy_sect
resultat_exploitation_ratio_2020_moy_sect
resultat_exploitation_ratio_2019_moy_sect
resultat_exploitation_ratio_2018_moy_sect
revenue_2022_moy_sect
net_result_2022_moy_sect
equity_2022_moy_sect
roe_2022_moy_sect
net_debt_2022_moy_sect
current_assets_2022_moy_sect
current_liabilities_2022_moy_sect
solvability_ratio_2022_moy_sect
gross_operating_ebitda_2022_moy_sect
gross_operating_ebitda_ratio_2022_moy_sect
gross_operating_ebitda_ratio_moy_sect
reimbursement_ratio_2022_moy_sect
robustness_ratio_2022_moy_sect
resultat_exploitation_ratio_2022_moy_sect
resultat_d_exploitation_2021_moy_sect
resultat_d_exploitation_2020_moy_sect
resultat_d_exploitation_2019_moy_sect
resultat_d_exploitation_2018_moy_sect
resultat_d_exploitation_2022_moy_sect
resultat_exploitation_ratio_moy_sect
net_result_moy_sect
current_assets_moy_sect
equity_moy_sect
current_liabilities_moy_sect
revenue_moy_sect
reimbursement_ratio_moy_sect
robustness_ratio_moy_sect
solvability_ratio_moy_sect
net_debt_moy_sect
gross_operating_ebitda_moy_sect
CAGR_18_22_moy_sect
RCI_2018_moy_sect
RCI_2019_moy_sect
RCI_2020_moy_sect
RCI_2021_moy_sect
RCI_2022_moy_sect
RCI_moy_sect
total_fonds_moy_sect
equity_costs_moy_sect
RdtCpx_moy_sect
RdtCpx_2018_moy_sect
RdtCpx_2019_moy_sect
RdtCpx_2020_moy_sect
RdtCpx_2021_moy_sect
RdtCpx_2022_moy_sect

In [205]:
# Supprimer les lignes dont l'index est NaN et créer une colonne ape à partir de l index
moyennes_par_secteur = moyennes_par_secteur.dropna(axis='index', how='all')
moyennes_par_secteur['ape_code'] = moyennes_par_secteur.index

In [206]:
moyennes_par_secteur.head(10)

,capital_moy_sect,enrollment_moy_sect,last_number_of_employees_moy_sect,employees_number_for_linkedin_moy_sect,revenue_2021_moy_sect,revenue_2020_moy_sect,revenue_2019_moy_sect,revenue_2018_moy_sect,net_result_2021_moy_sect,equity_2021_moy_sect,...,RCI_moy_sect,total_fonds_moy_sect,equity_costs_moy_sect,RdtCpx_moy_sect,RdtCpx_2018_moy_sect,RdtCpx_2019_moy_sect,RdtCpx_2020_moy_sect,RdtCpx_2021_moy_sect,RdtCpx_2022_moy_sect,ape_code
0240Z,6018867.0,164.0,164.0,31450.0,20935648.0,19625720.0,1.957447e+07,1.878787e+07,2.144226e+06,12864427.0,...,0.022279,5.086656e+07,0.039637,0.077341,0.108128,0.008002,-0.015068,0.166679,NaN,0240Z
0311Z,3100.0,30.0,30.0,30.0,5962535.0,4823971.0,NaN,4.426720e+06,3.014700e+04,115808.0,...,0.010191,1.084393e+06,0.031780,0.260319,NaN,NaN,NaN,0.260319,NaN,0311Z
0812Z,13153864.0,518.0,518.0,11.5,192021888.0,141663305.0,1.599952e+08,1.584895e+08,9.279078e+06,113049208.0,...,-1.331072,1.820742e+08,0.057607,0.106368,0.107565,0.107121,0.065864,0.136118,0.087751,0812Z
0893Z,68040000.0,527.0,527.0,331.0,159411000.0,147622000.0,1.492200e+08,1.442490e+08,1.484200e+07,128990000.0,...,-1.235475,2.375492e+08,0.055676,0.091171,0.074688,0.078957,0.093255,0.115063,0.081468,0893Z
1012Z,2000000.0,275.0,275.0,64.0,78860050.0,68368140.0,6.051014e+07,5.798769e+07,3.575590e+05,2047703.0,...,-0.020025,2.394488e+07,0.033512,-0.121008,-0.534845,-0.350265,0.072845,0.174615,NaN,1012Z
1013A,576212.0,62.5,62.5,25.0,13177617.5,14604399.0,9.510418e+06,9.903131e+06,5.635715e+05,1934685.5,...,-0.046574,6.714625e+06,0.042247,0.034308,0.107213,-0.025670,0.167574,-0.025162,0.189514,1013A
1020Z,701060.0,75.0,75.0,NaN,9752274.0,7505844.0,6.803573e+06,6.961143e+06,2.822370e+05,3567775.0,...,3.699173,3.205781e+06,0.054979,0.096085,NaN,0.117425,NaN,0.079107,NaN,1020Z
1031Z,6816184.0,149.0,149.0,NaN,24286428.0,22074559.0,1.366335e+07,NaN,-6.158341e+06,6130504.0,...,9.910650,1.516055e+07,0.050135,-0.870680,NaN,-0.720041,-0.857402,-1.004541,NaN,1031Z
1039B,974958.5,58.0,58.0,34.0,43117689.0,28782893.5,2.930102e+07,2.946296e+07,9.568750e+05,16771704.0,...,1.230035,1.616034e+07,0.061828,0.092119,0.128893,0.090010,0.069290,0.057053,NaN,1039B
1051A,33915064.0,646.0,646.0,324.5,351032661.5,344900321.0,3.299671e+08,3.265091e+08,9.471216e+06,137221865.5,...,0.237963,2.537726e+08,0.052052,0.113654,-0.000141,0.027475,0.156053,0.179950,NaN,1051A

In [207]:
liste_colonnes = ['capital','enrollment','last_number_of_employees','employees_number_for_linkedin','revenue_2021',
                  'revenue_2020','revenue_2019','revenue_2018','net_result_2021','equity_2021','roe_2021','net_debt_2021',
                  'current_assets_2021','current_liabilities_2021','solvability_ratio_2021','gross_operating_ebitda_2021',
                  'gross_operating_ebitda_ratio_2021','reimbursement_ratio_2021','robustness_ratio_2021','net_result_2020',
                  'equity_2020','roe_2020','net_debt_2020','current_assets_2020','current_liabilities_2020',
                  'solvability_ratio_2020','gross_operating_ebitda_2020','gross_operating_ebitda_ratio_2020',
                  'reimbursement_ratio_2020','robustness_ratio_2020','net_result_2019','equity_2019','roe_2019',
                  'net_debt_2019','current_assets_2019','current_liabilities_2019','solvability_ratio_2019',
                  'gross_operating_ebitda_2019','gross_operating_ebitda_ratio_2019','reimbursement_ratio_2019',
                  'robustness_ratio_2019','net_result_2018','equity_2018','roe_2018','net_debt_2018','current_assets_2018',
                  'current_liabilities_2018','solvability_ratio_2018','gross_operating_ebitda_2018',
                  'gross_operating_ebitda_ratio_2018','reimbursement_ratio_2018','robustness_ratio_2018',
                  'growth_ratio_2021','growth_ratio_2020','growth_ratio_2019','societeinfo_growth_ratio_2022','resultat_exploitation_ratio_2021',
                  'resultat_exploitation_ratio_2020','resultat_exploitation_ratio_2019','resultat_exploitation_ratio_2018',
                  'revenue_2022','net_result_2022','equity_2022','roe_2022','net_debt_2022','current_assets_2022',
                  'current_liabilities_2022','solvability_ratio_2022','gross_operating_ebitda_2022',
                  'gross_operating_ebitda_ratio_2022','gross_operating_ebitda_ratio','reimbursement_ratio_2022',
                  'robustness_ratio_2022','resultat_exploitation_ratio_2022','resultat_d_exploitation_2021',
                  'resultat_d_exploitation_2020','resultat_d_exploitation_2019','resultat_d_exploitation_2018',
                  'resultat_d_exploitation_2022','resultat_exploitation_ratio','net_result','current_assets','equity',
                  'current_liabilities','revenue','reimbursement_ratio','robustness_ratio','solvability_ratio','net_debt',
                  'gross_operating_ebitda','CAGR_18_22','RCI_2018','RCI_2019','RCI_2020','RCI_2021','RCI_2022','RCI',
                  'total_fonds','equity_costs','RdtCpx','RdtCpx_2018','RdtCpx_2019','RdtCpx_2020','RdtCpx_2021','RdtCpx_2022']  

resultats = []  # Pour stocker les résultats après filtrage et calcul de la moyenne

# Itérer à travers chaque groupe
for nom_groupe, groupe in nouveau_source_entreprise.groupby('ape_code'):
    Q1 = groupe[liste_colonnes].quantile(0.25)
    Q3 = groupe[liste_colonnes].quantile(0.75)
    IQR = Q3 - Q1
    
    # Filtrer les valeurs extrêmes dans le groupe
    filtre = ~((groupe[liste_colonnes] < (Q1 - 1.5 * IQR)) | (groupe[liste_colonnes] > (Q3 + 1.5 * IQR))).any(axis=1)
    donnees_filtrees = groupe[filtre]
    
    # Calculer la somme pour le groupe filtré et l'ajouter à la liste des résultats
    sum_groupe = donnees_filtrees[liste_colonnes].sum()
    sum_groupe.name = nom_groupe  # Nommer la série de moyennes après le code du groupe
    resultats.append(sum_groupe)

# Combinez tous les résultats de groupe dans un nouveau DataFrame
total_par_secteur = pd.DataFrame(resultats)

C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4575: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4575: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4575: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4575: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4575: RuntimeWarning: invalid value encountered in multiply
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4575: RuntimeWarning: invalid value encountered in add
  lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
C:\Users\chris\anaconda3\Lib\site-packages\numpy\lib\function_base.py:4576: RuntimeWarning: invalid value encountered in subtract
  subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)

In [208]:
def renommer_colonnessum_selectionnees(dataframe, colonnes_a_renommer):
    # Créez un dictionnaire pour mapper les anciens noms aux nouveaux noms
    colonnes_renommees = {colonne: colonne + "_sum" for colonne in colonnes_a_renommer}
    
    # Utilisez la méthode rename() pour renommer les colonnes sélectionnées du DataFrame
    dataframe.rename(columns=colonnes_renommees, inplace=True)
    
    return dataframe

colonnes_a_renommer= liste_colonnes
total_par_secteur = renommer_colonnessum_selectionnees(total_par_secteur, colonnes_a_renommer)

In [201]:
colonnes = list(total_par_secteur.columns)
for colonne in colonnes:
    print(colonne)

capital_sum
enrollment_sum
last_number_of_employees_sum
employees_number_for_linkedin_sum
revenue_2021_sum
revenue_2020_sum
revenue_2019_sum
revenue_2018_sum
net_result_2021_sum
equity_2021_sum
roe_2021_sum
net_debt_2021_sum
current_assets_2021_sum
current_liabilities_2021_sum
solvability_ratio_2021_sum
gross_operating_ebitda_2021_sum
gross_operating_ebitda_ratio_2021_sum
reimbursement_ratio_2021_sum
robustness_ratio_2021_sum
net_result_2020_sum
equity_2020_sum
roe_2020_sum
net_debt_2020_sum
current_assets_2020_sum
current_liabilities_2020_sum
solvability_ratio_2020_sum
gross_operating_ebitda_2020_sum
gross_operating_ebitda_ratio_2020_sum
reimbursement_ratio_2020_sum
robustness_ratio_2020_sum
net_result_2019_sum
equity_2019_sum
roe_2019_sum
net_debt_2019_sum
current_assets_2019_sum
current_liabilities_2019_sum
solvability_ratio_2019_sum
gross_operating_ebitda_2019_sum
gross_operating_ebitda_ratio_2019_sum
reimbursement_ratio_2019_sum
robustness_ratio_2019_sum
net_result_2018_sum
equity_2018_sum
roe_2018_sum
net_debt_2018_sum
current_assets_2018_sum
current_liabilities_2018_sum
solvability_ratio_2018_sum
gross_operating_ebitda_2018_sum
gross_operating_ebitda_ratio_2018_sum
reimbursement_ratio_2018_sum
robustness_ratio_2018_sum
growth_ratio_2021_sum
growth_ratio_2020_sum
growth_ratio_2019_sum
societeinfo_growth_ratio_2022_sum
resultat_exploitation_ratio_2021_sum
resultat_exploitation_ratio_2020_sum
resultat_exploitation_ratio_2019_sum
resultat_exploitation_ratio_2018_sum
revenue_2022_sum
net_result_2022_sum
equity_2022_sum
roe_2022_sum
net_debt_2022_sum
current_assets_2022_sum
current_liabilities_2022_sum
solvability_ratio_2022_sum
gross_operating_ebitda_2022_sum
gross_operating_ebitda_ratio_2022_sum
gross_operating_ebitda_ratio_sum
reimbursement_ratio_2022_sum
robustness_ratio_2022_sum
resultat_exploitation_ratio_2022_sum
resultat_d_exploitation_2021_sum
resultat_d_exploitation_2020_sum
resultat_d_exploitation_2019_sum
resultat_d_exploitation_2018_sum
resultat_d_exploitation_2022_sum
resultat_exploitation_ratio_sum
net_result_sum
current_assets_sum
equity_sum
current_liabilities_sum
revenue_sum
reimbursement_ratio_sum
robustness_ratio_sum
solvability_ratio_sum
net_debt_sum
gross_operating_ebitda_sum
CAGR_18_22_sum
RCI_2018_sum
RCI_2019_sum
RCI_2020_sum
RCI_2021_sum
RCI_2022_sum
RCI_sum
total_fonds_sum
equity_costs_sum
RdtCpx_sum
RdtCpx_2018_sum
RdtCpx_2019_sum
RdtCpx_2020_sum
RdtCpx_2021_sum
RdtCpx_2022_sum

In [209]:
# Supprimer les lignes dont l'index est NaN et créer une colonne ape à partir de l index

total_par_secteur = total_par_secteur.dropna(axis='index', how='all')
total_par_secteur['ape_code'] = total_par_secteur.index

In [210]:
total_par_secteur.head(10)

,capital_sum,enrollment_sum,last_number_of_employees_sum,employees_number_for_linkedin_sum,revenue_2021_sum,revenue_2020_sum,revenue_2019_sum,revenue_2018_sum,net_result_2021_sum,equity_2021_sum,...,RCI_sum,total_fonds_sum,equity_costs_sum,RdtCpx_sum,RdtCpx_2018_sum,RdtCpx_2019_sum,RdtCpx_2020_sum,RdtCpx_2021_sum,RdtCpx_2022_sum,ape_code
0240Z,6018867.0,164.0,164.0,31450.0,20935648.0,19625720.0,19574466.0,18787869.0,2144226.0,12864427.0,...,0.022279,5.086656e+07,0.039637,0.077341,0.108128,0.008002,-0.015068,0.166679,0.000000,0240Z
0311Z,3100.0,30.0,30.0,30.0,5962535.0,4823971.0,0.0,4426720.0,30147.0,115808.0,...,0.010191,1.084393e+06,0.031780,0.260319,0.000000,0.000000,0.000000,0.260319,0.000000,0311Z
0812Z,39461592.0,1554.0,1554.0,23.0,576065664.0,424989915.0,479985703.0,475468387.0,27837233.0,339147624.0,...,-3.993216,5.462225e+08,0.172822,0.319104,0.322694,0.321362,0.197592,0.408355,0.087751,0812Z
0893Z,68040000.0,527.0,527.0,331.0,159411000.0,147622000.0,149220000.0,144249000.0,14842000.0,128990000.0,...,-1.235475,2.375492e+08,0.055676,0.091171,0.074688,0.078957,0.093255,0.115063,0.081468,0893Z
1011Z,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1011Z
1012Z,2000000.0,275.0,275.0,64.0,78860050.0,68368140.0,60510143.0,57987688.0,357559.0,2047703.0,...,-0.020025,2.394488e+07,0.033512,-0.121008,-0.534845,-0.350265,0.072845,0.174615,0.000000,1012Z
1013A,1152424.0,125.0,125.0,50.0,26355235.0,14604399.0,19020836.0,19806262.0,1127143.0,3869371.0,...,-0.093149,1.342925e+07,0.084493,0.068615,0.214426,-0.051339,0.167574,-0.050324,0.189514,1013A
1020Z,701060.0,75.0,75.0,0.0,9752274.0,7505844.0,6803573.0,6961143.0,282237.0,3567775.0,...,3.699173,3.205781e+06,0.054979,0.096085,0.000000,0.117425,0.000000,0.079107,0.000000,1020Z
1031Z,6816184.0,149.0,149.0,0.0,24286428.0,22074559.0,13663350.0,0.0,-6158341.0,6130504.0,...,9.910650,1.516055e+07,0.050135,-0.870680,0.000000,-0.720041,-0.857402,-1.004541,0.000000,1031Z
1039B,1949917.0,116.0,116.0,68.0,43117689.0,57565787.0,58602031.0,58925929.0,956875.0,16771704.0,...,2.460070,3.232067e+07,0.123655,0.184239,0.257785,0.180020,0.138580,0.057053,0.000000,1039B

In [211]:
resultat_final = pd.merge(nouveau_source_entreprise, moyennes_par_secteur, on='ape_code', how='inner')

In [212]:
secteur_db = pd.merge(moyennes_par_secteur, total_par_secteur, on='ape_code', how='inner')
secteur_db = secteur_db.copy()  # Création d'une copie pour défragmenter

In [213]:

secteur_db.to_csv('base_secteur_initiale.csv', index='ape_code')

In [214]:

nouveau_source_entreprise.to_csv('base_source_initiale.csv', index='siren')