In [3]:
import pandas as pd
import chardet

In [4]:
with open('extract_07022024-base_source.csv', 'rb') as f:
    result = chardet.detect(f.read())
    encoding = result['encoding']

print("Encodage détecté:", encoding)

Encodage détecté: Windows-1254

In [5]:
#referentiel base source
source_entreprise=pd.read_csv('extract_07022024-base_source.csv', encoding='utf-8', sep=',', on_bad_lines='skip')
source_entreprise.shape

C:\Users\chris\AppData\Local\Temp\ipykernel_7240\3033168289.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  source_entreprise=pd.read_csv('extract_07022024-base_source.csv', encoding='utf-8', sep=',', on_bad_lines='skip')

(11147, 179)

In [6]:
def renommer_colbase_source_selectionnees(dataframe, colonnes_a_renommer):
    # Créez un dictionnaire pour mapper les anciens noms aux nouveaux noms
    colonnes_renommees = {}
    for colonne in colonnes_a_renommer:
        nouveau_nom = colonne
        if colonne.startswith("societeinfo_"):
            nouveau_nom = nouveau_nom.replace("societeinfo_", "")
        if colonne.startswith("papers_"):
            nouveau_nom = nouveau_nom.replace("papers_", "")
        colonnes_renommees[colonne] = nouveau_nom
    
    # Utilisez la méthode rename() pour renommer les colonnes sélectionnées du DataFrame
    dataframe = dataframe.rename(columns=colonnes_renommees)
    
    return dataframe
colonnes_a_renommer=['papers_beneficiaires_effectifs','papers_bodacc_important_message',
                     'papers_derniere_mise_a_jour_rcs','papers_derniere_mise_a_jour_sirene',
                     'papers_marques','papers_procedures_collectives','papers_publications_bodacc',
                     'papers_representants','papers_resultat_d_exploitation_2018','papers_resultat_d_exploitation_2019',
                     'papers_resultat_d_exploitation_2020','papers_resultat_d_exploitation_2021',
                     'papers_resultat_d_exploitation_2022','papers_siren','societeinfo_ape_code','societeinfo_ape_name',
                     'societeinfo_capital','societeinfo_commercial_name','societeinfo_company_name',
                     'societeinfo_corporate_object','societeinfo_corporate_officer_birth_date',
                     'societeinfo_corporate_officer_name','societeinfo_corporate_officer_role','societeinfo_creation_date',
                     'societeinfo_current_assets_2018','societeinfo_current_assets_2019',
                     'societeinfo_current_assets_2020','societeinfo_current_assets_2021','societeinfo_current_assets_2022',
                     'societeinfo_current_liabilities_2018','societeinfo_current_liabilities_2019',
                     'societeinfo_current_liabilities_2020','societeinfo_current_liabilities_2021',
                     'societeinfo_current_liabilities_2022','societeinfo_employees_number_for_linkedin',
                     'societeinfo_enrollment','societeinfo_equity_2018','societeinfo_equity_2019',
                     'societeinfo_equity_2020','societeinfo_equity_2021','societeinfo_equity_2022',
                     'societeinfo_facebook_url','societeinfo_glassdoor_avis','societeinfo_glassdoor_notation',
                     'societeinfo_google_business_nb_avis','societeinfo_google_business_notation',
                     'societeinfo_google_business_resultats','societeinfo_google_search_description',
                     'societeinfo_google_search_keyword','societeinfo_greffe_name',
                     'societeinfo_gross_operating_ebitda_2018','societeinfo_gross_operating_ebitda_2019',
                     'societeinfo_gross_operating_ebitda_2020','societeinfo_gross_operating_ebitda_2021',
                     'societeinfo_gross_operating_ebitda_2022','societeinfo_gross_operating_ebitda_ratio_2018',
                     'societeinfo_gross_operating_ebitda_ratio_2019','societeinfo_gross_operating_ebitda_ratio_2020',
                     'societeinfo_gross_operating_ebitda_ratio_2021','societeinfo_gross_operating_ebitda_ratio_2022',
                     'societeinfo_growth_ratio_2019','societeinfo_growth_ratio_2020','societeinfo_growth_ratio_2021',
                     'societeinfo_growth_ratio_022','societeinfo_indeed_about_content','societeinfo_indeed_job_results',
                     'societeinfo_indeed_job_results_count','societeinfo_instagram_url','societeinfo_last_bodacc',
                     'societeinfo_last_number_of_employees','societeinfo_legal_company_form','societeinfo_linkedin_jobs',
                     'societeinfo_linkedin_posts','societeinfo_logo','societeinfo_net_debt_2018',
                     'societeinfo_net_debt_2019','societeinfo_net_debt_2020','societeinfo_net_debt_2021',
                     'societeinfo_net_debt_2022','societeinfo_net_result_2018','societeinfo_net_result_2019',
                     'societeinfo_net_result_2020','societeinfo_net_result_2021','societeinfo_net_result_2022',
                     'societeinfo_opportunities_of_the_siret','societeinfo_postal_address_city',
                     'societeinfo_postal_address_country','societeinfo_postal_address_country_code',
                     'societeinfo_postal_address_lat','societeinfo_postal_address_lng',
                     'societeinfo_postal_address_postal_address_additional_name','societeinfo_postal_address_postal_code',
                     'societeinfo_postal_address_street','societeinfo_range_employee_for_linkedin',
                     'societeinfo_reimbursement_ratio_2018','societeinfo_reimbursement_ratio_2019',
                     'societeinfo_reimbursement_ratio_2020','societeinfo_reimbursement_ratio_2021',
                     'societeinfo_reimbursement_ratio_2022','societeinfo_resultat_exploitation_ratio_2018',
                     'societeinfo_resultat_exploitation_ratio_2019','societeinfo_resultat_exploitation_ratio_2020',
                     'societeinfo_resultat_exploitation_ratio_2021','societeinfo_resultat_exploitation_ratio_2022',
                     'societeinfo_revenue_2018','societeinfo_revenue_2019','societeinfo_revenue_2020',
                     'societeinfo_revenue_2021','societeinfo_revenue_2022','societeinfo_robustness_ratio_2018',
                     'societeinfo_robustness_ratio_2019','societeinfo_robustness_ratio_2020',
                     'societeinfo_robustness_ratio_2021','societeinfo_robustness_ratio_2022','societeinfo_roe_2018',
                     'societeinfo_roe_2019','societeinfo_roe_2020','societeinfo_roe_2021','societeinfo_roe_2022',
                     'societeinfo_siren','societeinfo_siret','societeinfo_solvability_ratio_2018',
                     'societeinfo_solvability_ratio_2019','societeinfo_solvability_ratio_2020',
                     'societeinfo_solvability_ratio_2021','societeinfo_solvability_ratio_2022',
                     'societeinfo_strenghts_of_the_siret','societeinfo_threats_of_the_siret','societeinfo_twitter_url',
                     'societeinfo_vat_number','societeinfo_weaknesses_of_the_siret','societeinfo_web_scrap',
                     'societeinfo_web_site_url']

                     # Appliquer la fonction pour renommer les colonnes
source_entreprise = renommer_colbase_source_selectionnees(source_entreprise, colonnes_a_renommer)

In [38]:
# type d entreprise selon nombre de salariés
def determine_type_ent(enrollment):
    if enrollment < 3:
        return 'microentreprise'
    elif 3 <= enrollment <= 10:
        return 'TPE'
    elif 11 <= enrollment <= 250:
        return 'PME'
    elif 251 <= enrollment <= 5000:
        return 'ETI'
    else:  # enrollment > 2500
        return 'GE'
source_entreprise['type_ent'] = source_entreprise['enrollment'].apply(determine_type_ent)

# Convertir la colonne "creation_date" en type datetime / Extraire l'année et créer une nouvelle colonn
source_entreprise['creation_date'] = pd.to_datetime(source_entreprise['creation_date'])
source_entreprise['creation_year'] = source_entreprise['creation_date'].dt.year

# Supprimer la seconde colonne 'ape_code' dupliquée
source_entreprise = source_entreprise.loc[:, ~source_entreprise.columns.duplicated()]

# ratio moyen 2018-2022
source_entreprise['resultat_exploitation_ratio'] = source_entreprise[['resultat_exploitation_ratio_2021', 'resultat_exploitation_ratio_2020', 'resultat_exploitation_ratio_2019', 'resultat_exploitation_ratio_2018']].mean(axis=1)
source_entreprise['net_result'] = source_entreprise[['net_result_2021', 'net_result_2020', 'net_result_2019', 'net_result_2018']].mean(axis=1)
source_entreprise['current_assets'] = source_entreprise[['current_assets_2021', 'current_assets_2020', 'current_assets_2019', 'current_assets_2018']].mean(axis=1)
source_entreprise['equity'] = source_entreprise[['equity_2021', 'equity_2020', 'equity_2019', 'equity_2018']].mean(axis=1)
source_entreprise['current_liabilities'] = source_entreprise[['current_liabilities_2021', 'current_liabilities_2020', 'current_liabilities_2019', 'current_liabilities_2018']].mean(axis=1)
source_entreprise['revenue'] = source_entreprise[['revenue_2018', 'revenue_2019', 'revenue_2020', 'revenue_2021', 'revenue_2022']].mean(axis=1)
source_entreprise['reimbursement_ratio'] = source_entreprise[['reimbursement_ratio_2018', 'reimbursement_ratio_2019', 'reimbursement_ratio_2020', 'reimbursement_ratio_2021', 'reimbursement_ratio_2022']].mean(axis=1)
source_entreprise['robustness_ratio'] = source_entreprise[['robustness_ratio_2018', 'robustness_ratio_2019', 'robustness_ratio_2020', 'robustness_ratio_2021', 'robustness_ratio_2022']].mean(axis=1)
source_entreprise['solvability_ratio'] = source_entreprise[['solvability_ratio_2018', 'solvability_ratio_2019', 'solvability_ratio_2020', 'solvability_ratio_2021', 'solvability_ratio_2022']].mean(axis=1)
source_entreprise['net_debt'] = source_entreprise[['net_debt_2018', 'net_debt_2019', 'net_debt_2020', 'net_debt_2021', 'net_debt_2022']].mean(axis=1)
source_entreprise['gross_operating_ebitda'] = source_entreprise[['gross_operating_ebitda_2021', 'gross_operating_ebitda_2020', 'gross_operating_ebitda_2019', 'gross_operating_ebitda_2018']].mean(axis=1)
source_entreprise['gross_operating_ebitda_ratio'] = source_entreprise[['gross_operating_ebitda_ratio_2021', 'gross_operating_ebitda_ratio_2020', 'gross_operating_ebitda_ratio_2019', 'gross_operating_ebitda_ratio_2018']].mean(axis=1)
source_entreprise['CAGR_18_22'] = source_entreprise[['growth_ratio_2021', 'growth_ratio_2020', 'growth_ratio_2019']].mean(axis=1)

#hypothese taux interet de la dette à 3% / taux de rendement des actionnaires à 8%
source_entreprise['RCI_2018']=source_entreprise['net_result_2018']/(source_entreprise['current_assets_2018']-source_entreprise['current_liabilities_2018'])
source_entreprise['RCI_2019']=source_entreprise['net_result_2019']/(source_entreprise['current_assets_2019']-source_entreprise['current_liabilities_2019'])
source_entreprise['RCI_2020']=source_entreprise['net_result_2020']/(source_entreprise['current_assets_2020']-source_entreprise['current_liabilities_2020'])
source_entreprise['RCI_2021']=source_entreprise['net_result_2021']/(source_entreprise['current_assets_2021']-source_entreprise['current_liabilities_2021'])
source_entreprise['RCI_2022']=source_entreprise['net_result_2022']/(source_entreprise['current_assets_2022']-source_entreprise['current_liabilities_2022'])
source_entreprise['RCI']=source_entreprise['net_result']/(source_entreprise['current_assets']-source_entreprise['current_liabilities'])
source_entreprise['total_fonds']=source_entreprise['equity']+source_entreprise['net_debt']
source_entreprise['equity_costs']=(source_entreprise['equity']/source_entreprise['total_fonds']*0.08)+(source_entreprise['net_debt']/source_entreprise['total_fonds']*0.03)
source_entreprise['taux de recrutement']=(source_entreprise['indeed_job_results_count']/source_entreprise['enrollment'])
source_entreprise['RdtCpx_2018']=source_entreprise['net_result_2018']/(source_entreprise['equity_2018'])
source_entreprise['RdtCpx_2019']=source_entreprise['net_result_2019']/(source_entreprise['equity_2019'])
source_entreprise['RdtCpx_2020']=source_entreprise['net_result_2020']/(source_entreprise['equity_2020'])
source_entreprise['RdtCpx_2021']=source_entreprise['net_result_2021']/(source_entreprise['equity_2021'])
source_entreprise['RdtCpx_2022']=source_entreprise['net_result_2022']/(source_entreprise['equity_2022'])
source_entreprise['RdtCpx']=source_entreprise['net_result']/(source_entreprise['equity'])
source_entreprise['FRN_2018']=source_entreprise['current_assets_2018']-(source_entreprise['current_liabilities_2018'])
source_entreprise['FRN_2019']=source_entreprise['current_assets_2019']-(source_entreprise['current_liabilities_2019'])
source_entreprise['FRN_2020']=source_entreprise['current_assets_2020']-(source_entreprise['current_liabilities_2020'])
source_entreprise['FRN_2021']=source_entreprise['current_assets_2021']-(source_entreprise['current_liabilities_2021'])
source_entreprise['FRN_2022']=source_entreprise['current_assets_2022']-(source_entreprise['current_liabilities_2022'])
source_entreprise['FRN']=source_entreprise['current_assets']-(source_entreprise['current_liabilities'])

In [39]:
# Définir la valeur seuil
valeur_plafond = 1000000000  # 10 millions

# Créer un nouveau DataFrame avec les lignes où la colonne 'revenue' est inférieur au plafond
nouveau_source_entreprise = source_entreprise[source_entreprise['revenue'] < valeur_plafond]

# decrit la moyenne des revenues en arrondissant à deux chiffres après la virgule
(nouveau_source_entreprise['revenue'].describe() / 1e6).round(2)

count      0.01
mean      45.17
std      107.23
min        0.00
25%        5.74
50%       12.02
75%       33.01
max      996.36
Name: revenue, dtype: float64

In [40]:
colonnes = list(source_entreprise.columns)
for colonne in colonnes:
    print(colonne)

estimated_revenue_estimated_revenue_2020
instagram_url
ape_code
indeed_about_content
banking_data_solde_credit_equipement
net_result_2018
cartography_liens_entreprises_personnes
derniere_mise_a_jour_rcs
banking_data_bdf_score
revenue_2020
additional_info_naf_code
estimated_revenue_average_growth_of_the_siren
revenue_2022
solvability_ratio_2019
corporate_officer_name
estimated_revenue_estimated_revenue_2021
estimated_revenue_estimated_growth_2023
gross_operating_ebitda_ratio_2018
company_name
ape_name
banking_data_insurance_locaux
current_liabilities_2020
banking_data_is_significantly_changing
cartography_error
banking_data_solde_courant_moyen
beneficiaires_effectifs
banking_data_insurance_vehicules_pro
marques
equity_2021
resultat_exploitation_ratio_2022
opportunities_of_the_siret
gross_operating_ebitda_2020
web_scrap
postal_address_postal_address_additional_name
strenghts_of_the_siret
current_liabilities_2018
last_number_of_employees
gross_operating_ebitda_ratio_2019
google_search_keyword
linkedin_posts
cartography_liens_entreprises_entreprises
enrollment
corporate_object
solvability_ratio_2020
net_result_2020
equity_2022
current_assets_2022
gross_operating_ebitda_ratio_2021
bodacc_important_message
postal_address_street
current_liabilities_2019
gross_operating_ebitda_ratio_2022
banking_data_flux_3m
reimbursement_ratio_2018
corporate_officer_birth_date
legal_company_form
net_result_2022
last_bodacc
employees_number_for_linkedin
net_result_2021
linkedin_jobs
postal_address_lat
solvability_ratio_2018
google_search_description
estimated_revenue_segment_of_the_siren
banking_data_denomination
company_name_index
estimated_revenue_estimated_revenue_2019
range_employee_for_linkedin
glassdoor_avis
banking_data_flux_1m
gross_operating_ebitda_2021
current_liabilities_2022
web_site_url
twitter_url
web_infos_synthesis
cartography_message
additional_info_region
web_infos_narrative
equity_2018
logo
estimated_revenue_estimated_revenue_2022
cartography_entreprises
growth_ratio_2021
resultat_exploitation_ratio_2019
capital
resultat_exploitation_ratio_2020
roe_2022
net_debt_2021
current_assets_2020
corporate_officer_role
revenue_2021
growth_ratio_2020
resultat_d_exploitation_2019
indeed_job_results_count
google_business_notation
additional_info_region_code
weaknesses_of_the_siret
banking_data_atradius_score
banking_data_flux_1y
google_business_nb_avis
robustness_ratio_2018
current_assets_2019
net_debt_2020
web_infos_news_positiveness
net_debt_2022
banking_data_flux_6m
reimbursement_ratio_2022
equity_2019
estimated_revenue_siren
banking_data_solde_placement
roe_2021
cartography_personnes
banking_data_insurance_sinistres
roe_2019
robustness_ratio_2021
growth_ratio_2019
current_assets_2018
net_debt_2018
cartography_statusCode
siren
commercial_name
current_assets_2021
google_business_resultats
robustness_ratio_2020
facebook_url
siret
representants
robustness_ratio_2022
revenue_2019
gross_operating_ebitda_2018
gross_operating_ebitda_2019
current_liabilities_2021
resultat_exploitation_ratio_2018
net_debt_2019
estimated_revenue_average_ebe_of_the_siren
banking_data_insurance_lies_a_activite
estimated_revenue_estimated_revenue_2023
publications_bodacc
postal_address_city
postal_address_postal_code
net_result_2019
resultat_d_exploitation_2021
glassdoor_notation
societeinfo_growth_ratio_2022
reimbursement_ratio_2020
roe_2018
banking_data_is_multi_bank
gross_operating_ebitda_2022
vat_number
creation_date
indeed_job_results
equity_2020
reimbursement_ratio_2019
revenue_2018
region_index
postal_address_lng
solvability_ratio_2021
pfs_id
banking_data_insurance_salaries
postal_address_country
resultat_exploitation_ratio_2021
postal_address_country_code
derniere_mise_a_jour_sirene
reimbursement_ratio_2021
banking_data_siren
resultat_d_exploitation_2022
resultat_d_exploitation_2020
solvability_ratio_2022
roe_2020
banking_data_siret
resultat_d_exploitation_2018
threats_of_the_siret
gross_operating_ebitda_ratio_2020
greffe_name
robustness_ratio_2019
procedures_collectives
type_ent
creation_year
resultat_exploitation_ratio
net_result
current_assets
equity
current_liabilities
revenue
reimbursement_ratio
robustness_ratio
solvability_ratio
net_debt
gross_operating_ebitda
gross_operating_ebitda_ratio
CAGR_18_22
RCI_2018
RCI_2019
RCI_2020
RCI_2021
RCI_2022
RCI
total_fonds
equity_costs
taux de recrutement
RdtCpx_2018
RdtCpx_2019
RdtCpx_2020
RdtCpx_2021
RdtCpx_2022
RdtCpx
FRN_2018
FRN_2019
FRN_2020
FRN_2021
FRN_2022
FRN

In [41]:
nouveau_source_entreprise.shape

(9993, 213)

In [42]:
# nombre d entreprise par annee de creation
ent_par_an=nouveau_source_entreprise.groupby('creation_year').count()
ent_par_an.head(5)

,estimated_revenue_estimated_revenue_2020,instagram_url,ape_code,indeed_about_content,banking_data_solde_credit_equipement,net_result_2018,cartography_liens_entreprises_personnes,derniere_mise_a_jour_rcs,banking_data_bdf_score,revenue_2020,...,RdtCpx_2020,RdtCpx_2021,RdtCpx_2022,RdtCpx,FRN_2018,FRN_2019,FRN_2020,FRN_2021,FRN_2022,FRN
creation_year,,,,,,,,,,,,,,,,,,,,,
1900.0,3,2,3,1,1,3,3,0,1,3,...,2,3,0,3,3,3,3,3,0,3
1901.0,14,9,14,0,0,14,14,4,0,14,...,13,12,3,13,14,14,14,12,3,14
1909.0,1,0,1,0,0,1,1,0,0,1,...,1,1,0,1,1,1,1,1,0,1
1910.0,1,1,1,0,0,1,1,1,0,1,...,1,0,0,1,1,1,1,0,0,1
1912.0,1,1,1,0,0,1,1,1,0,1,...,1,1,0,1,1,1,1,1,0,1

In [43]:
# decrit la moyenne des revenues en arrondissant à deux chiffres après la virgule
(nouveau_source_entreprise['revenue'].describe() / 1e6).round(2)

count      0.01
mean      45.17
std      107.23
min        0.00
25%        5.74
50%       12.02
75%       33.01
max      996.36
Name: revenue, dtype: float64

In [44]:
# Grouper par 'ape_code' et compter les occurrences
ent_par_ape = nouveau_source_entreprise.groupby('ape_code').count()

# Afficher les 5 premières lignes du DataFrame résultant
ent_par_ape.head(5)

,estimated_revenue_estimated_revenue_2020,instagram_url,indeed_about_content,banking_data_solde_credit_equipement,net_result_2018,cartography_liens_entreprises_personnes,derniere_mise_a_jour_rcs,banking_data_bdf_score,revenue_2020,additional_info_naf_code,...,RdtCpx_2020,RdtCpx_2021,RdtCpx_2022,RdtCpx,FRN_2018,FRN_2019,FRN_2020,FRN_2021,FRN_2022,FRN
ape_code,,,,,,,,,,,,,,,,,,,,,
0119Z,0,0,0,0,1,1,0,0,0,1,...,0,1,0,1,1,1,1,1,0,1
0240Z,1,1,0,0,1,1,0,0,1,1,...,1,1,0,1,1,1,1,1,0,1
0311Z,1,1,0,0,0,1,0,0,1,1,...,0,1,0,1,0,1,1,1,0,1
0812Z,3,2,0,0,3,3,1,0,3,3,...,3,3,1,3,3,3,3,3,1,3
0893Z,1,0,0,0,1,1,1,0,1,1,...,1,1,1,1,1,1,1,1,1,1

In [45]:
# Grouper par 'ape_code' et compter les occurrences
ent_par_ape = nouveau_source_entreprise.groupby('ape_code').count()

# Créer une nouvelle colonne 
nombre_ent_series = ent_par_ape['siren']
# Concaténer la colonne existante avec la nouvelle colonne dans une seule opération
ent_par_ape = pd.concat([ent_par_ape, nombre_ent_series.rename('nombre_ent')], axis=1)

In [46]:
moyennes_par_ape = nouveau_source_entreprise.groupby('ape_code')[['revenue', 'resultat_exploitation_ratio']].mean()
moyennes_par_ape['revenue'] = moyennes_par_ape['revenue'] / 1000000

# Réinitialiser l'index pour que 'ape_code' soit une colonne
moyennes_par_ape_reset = moyennes_par_ape.reset_index()
moyennes_par_ape=moyennes_par_ape_reset[['ape_code','revenue', 'resultat_exploitation_ratio']]

In [47]:
moyennes_par_ape.head(5)

  ape_code     revenue  resultat_exploitation_ratio
0    0119Z    8.529587                     0.059613
1    0240Z   19.730926                     0.026567
2    0311Z    5.071075                     0.005622
3    0812Z  163.230540                     0.079856
4    0893Z  153.180600                     0.110222

In [48]:
liste_colonnes = ['capital','enrollment','last_number_of_employees','employees_number_for_linkedin','revenue_2021','revenue_2020','revenue_2019','revenue_2018','net_result_2021','equity_2021','roe_2021','net_debt_2021','current_assets_2021','current_liabilities_2021','solvability_ratio_2021','gross_operating_ebitda_2021','gross_operating_ebitda_ratio_2021','reimbursement_ratio_2021','robustness_ratio_2021','net_result_2020','equity_2020','roe_2020','net_debt_2020','current_assets_2020','current_liabilities_2020','solvability_ratio_2020','gross_operating_ebitda_2020','gross_operating_ebitda_ratio_2020','reimbursement_ratio_2020','robustness_ratio_2020','net_result_2019','equity_2019','roe_2019','net_debt_2019','current_assets_2019','current_liabilities_2019','solvability_ratio_2019','gross_operating_ebitda_2019','gross_operating_ebitda_ratio_2019','reimbursement_ratio_2019','robustness_ratio_2019','net_result_2018','equity_2018','roe_2018','net_debt_2018','current_assets_2018','current_liabilities_2018','solvability_ratio_2018','gross_operating_ebitda_2018','gross_operating_ebitda_ratio_2018','reimbursement_ratio_2018','robustness_ratio_2018','growth_ratio_2021','growth_ratio_2020','growth_ratio_2019','resultat_exploitation_ratio_2021','resultat_exploitation_ratio_2020','resultat_exploitation_ratio_2019','resultat_exploitation_ratio_2018','revenue_2022','net_result_2022','equity_2022','roe_2022','net_debt_2022','current_assets_2022','current_liabilities_2022','solvability_ratio_2022','gross_operating_ebitda_2022','gross_operating_ebitda_ratio_2022','gross_operating_ebitda_ratio','reimbursement_ratio_2022','robustness_ratio_2022','resultat_exploitation_ratio_2022','resultat_d_exploitation_2021','resultat_d_exploitation_2020','resultat_d_exploitation_2019','resultat_d_exploitation_2018','resultat_d_exploitation_2022','resultat_exploitation_ratio','net_result','current_assets','equity','current_liabilities','revenue','reimbursement_ratio','robustness_ratio','solvability_ratio','net_debt','gross_operating_ebitda','CAGR_18_22','RCI_2018','RCI_2019','RCI_2020','RCI_2021','RCI_2022','RCI','total_fonds','equity_costs']  

# Grouper par secteur et calculer la moyenne des colonnes spécifiées
moyennes_par_secteur = nouveau_source_entreprise.groupby('ape_code')[liste_colonnes].mean()

# Grouper par secteur et calculer la moyenne des colonnes spécifiées
total_par_secteur = nouveau_source_entreprise.groupby('ape_code')[liste_colonnes].sum()

In [49]:
total_par_secteur.head(10)

,capital,enrollment,last_number_of_employees,employees_number_for_linkedin,revenue_2021,revenue_2020,revenue_2019,revenue_2018,net_result_2021,equity_2021,...,gross_operating_ebitda,CAGR_18_22,RCI_2018,RCI_2019,RCI_2020,RCI_2021,RCI_2022,RCI,total_fonds,equity_costs
ape_code,,,,,,,,,,,,,,,,,,,,,
0119Z,2000000.0,25.0,25.0,3.0,10764824.0,0.0,0.0,6294351.0,868968.0,4571736.0,...,4.278720e+05,0.000000,-0.063875,0.000000,0.000000,-0.688792,0.000000,-0.273470,5.085302e+06,0.058189
0240Z,6018867.0,164.0,164.0,31450.0,20935648.0,19625720.0,19574466.0,18787869.0,2144226.0,12864427.0,...,1.713029e+06,0.037077,0.019970,0.002357,-0.005044,0.066001,0.000000,0.022279,5.086656e+07,0.039637
0311Z,3100.0,30.0,30.0,30.0,5962535.0,4823971.0,0.0,4426720.0,30147.0,115808.0,...,2.372903e+05,0.236022,0.000000,0.000000,0.000000,0.010191,0.000000,0.010191,1.084393e+06,0.031780
0812Z,39461592.0,1554.0,1554.0,23.0,576065664.0,424989915.0,479985703.0,475468387.0,27837233.0,339147624.0,...,8.826522e+07,0.377094,-2.235668,-1.789319,-1.800916,-0.096533,-0.346764,-3.993216,5.462225e+08,0.172822
0893Z,68040000.0,527.0,527.0,331.0,159411000.0,147622000.0,149220000.0,144249000.0,14842000.0,128990000.0,...,2.756775e+07,0.034537,-0.220699,-0.574964,-0.582013,0.373835,4.832064,-1.235475,2.375492e+08,0.055676
1011Z,2183000.0,1646.0,1646.0,420.0,803102316.0,742271124.0,769061607.0,822603349.0,9757728.0,124625171.0,...,5.383706e+06,0.339461,-0.357029,0.139033,-0.168978,-1.880050,0.097344,-1.995378,6.545627e+07,0.188832
1012Z,2000000.0,275.0,275.0,64.0,78860050.0,68368140.0,60510143.0,57987688.0,357559.0,2047703.0,...,1.974132e+06,0.108941,-0.074790,-0.055125,0.011911,0.034962,0.000000,-0.020025,2.394488e+07,0.033512
1013A,1152424.0,125.0,125.0,50.0,26355235.0,14604399.0,19020836.0,19806262.0,1127143.0,3869371.0,...,1.458362e+06,0.212688,0.229101,-0.099450,0.105639,-0.295367,0.316760,-0.093149,1.342925e+07,0.084493
1020Z,701060.0,75.0,75.0,0.0,9752274.0,7505844.0,6803573.0,6961143.0,282237.0,3567775.0,...,5.205462e+05,0.126625,0.000000,9.191385,0.000000,2.168785,0.000000,3.699173,3.205781e+06,0.054979
1031Z,6816184.0,149.0,149.0,0.0,24286428.0,22074559.0,13663350.0,0.0,-6158341.0,6130504.0,...,-4.752974e+06,0.357902,0.000000,-2.886031,4.545639,4.361231,0.000000,9.910650,1.516055e+07,0.050135

In [50]:
moyennes_par_secteur.head(10)

,capital,enrollment,last_number_of_employees,employees_number_for_linkedin,revenue_2021,revenue_2020,revenue_2019,revenue_2018,net_result_2021,equity_2021,...,gross_operating_ebitda,CAGR_18_22,RCI_2018,RCI_2019,RCI_2020,RCI_2021,RCI_2022,RCI,total_fonds,equity_costs
ape_code,,,,,,,,,,,,,,,,,,,,,
0119Z,2000000.0,25.0,25.0,3.0,10764824.0,NaN,NaN,6.294351e+06,8.689680e+05,4.571736e+06,...,4.278720e+05,NaN,-0.063875,0.000000,NaN,-0.688792,NaN,-0.273470,5.085302e+06,0.058189
0240Z,6018867.0,164.0,164.0,31450.0,20935648.0,19625720.0,1.957447e+07,1.878787e+07,2.144226e+06,1.286443e+07,...,1.713029e+06,0.037077,0.019970,0.002357,-0.005044,0.066001,NaN,0.022279,5.086656e+07,0.039637
0311Z,3100.0,30.0,30.0,30.0,5962535.0,4823971.0,NaN,4.426720e+06,3.014700e+04,1.158080e+05,...,2.372903e+05,0.236022,NaN,NaN,NaN,0.010191,NaN,0.010191,1.084393e+06,0.031780
0812Z,13153864.0,518.0,518.0,11.5,192021888.0,141663305.0,1.599952e+08,1.584895e+08,9.279078e+06,1.130492e+08,...,2.942174e+07,0.125698,-0.745223,-0.596440,-0.600305,-0.032178,-0.346764,-1.331072,1.820742e+08,0.057607
0893Z,68040000.0,527.0,527.0,331.0,159411000.0,147622000.0,1.492200e+08,1.442490e+08,1.484200e+07,1.289900e+08,...,2.756775e+07,0.034537,-0.220699,-0.574964,-0.582013,0.373835,4.832064,-1.235475,2.375492e+08,0.055676
1011Z,545750.0,411.5,411.5,105.0,200775579.0,185567781.0,2.563539e+08,2.056508e+08,2.439432e+06,3.115629e+07,...,1.345926e+06,0.084865,-0.089257,0.069517,-0.056326,-0.626683,0.097344,-0.498844,1.636407e+07,0.047208
1012Z,2000000.0,275.0,275.0,64.0,78860050.0,68368140.0,6.051014e+07,5.798769e+07,3.575590e+05,2.047703e+06,...,1.974132e+06,0.108941,-0.074790,-0.055125,0.011911,0.034962,NaN,-0.020025,2.394488e+07,0.033512
1013A,576212.0,62.5,62.5,25.0,13177617.5,14604399.0,9.510418e+06,9.903131e+06,5.635715e+05,1.934686e+06,...,7.291808e+05,0.106344,0.114550,-0.049725,0.105639,-0.147683,0.316760,-0.046574,6.714625e+06,0.042247
1020Z,701060.0,75.0,75.0,NaN,9752274.0,7505844.0,6.803573e+06,6.961143e+06,2.822370e+05,3.567775e+06,...,5.205462e+05,0.126625,NaN,9.191385,NaN,2.168785,NaN,3.699173,3.205781e+06,0.054979
1031Z,6816184.0,149.0,149.0,NaN,24286428.0,22074559.0,1.366335e+07,NaN,-6.158341e+06,6.130504e+06,...,-4.752974e+06,0.357902,NaN,-2.886031,4.545639,4.361231,NaN,9.910650,1.516055e+07,0.050135

In [51]:
colonnes = list(moyennes_par_secteur.columns)
for colonne in colonnes:
    print(colonne)

capital
enrollment
last_number_of_employees
employees_number_for_linkedin
revenue_2021
revenue_2020
revenue_2019
revenue_2018
net_result_2021
equity_2021
roe_2021
net_debt_2021
current_assets_2021
current_liabilities_2021
solvability_ratio_2021
gross_operating_ebitda_2021
gross_operating_ebitda_ratio_2021
reimbursement_ratio_2021
robustness_ratio_2021
net_result_2020
equity_2020
roe_2020
net_debt_2020
current_assets_2020
current_liabilities_2020
solvability_ratio_2020
gross_operating_ebitda_2020
gross_operating_ebitda_ratio_2020
reimbursement_ratio_2020
robustness_ratio_2020
net_result_2019
equity_2019
roe_2019
net_debt_2019
current_assets_2019
current_liabilities_2019
solvability_ratio_2019
gross_operating_ebitda_2019
gross_operating_ebitda_ratio_2019
reimbursement_ratio_2019
robustness_ratio_2019
net_result_2018
equity_2018
roe_2018
net_debt_2018
current_assets_2018
current_liabilities_2018
solvability_ratio_2018
gross_operating_ebitda_2018
gross_operating_ebitda_ratio_2018
reimbursement_ratio_2018
robustness_ratio_2018
growth_ratio_2021
growth_ratio_2020
growth_ratio_2019
resultat_exploitation_ratio_2021
resultat_exploitation_ratio_2020
resultat_exploitation_ratio_2019
resultat_exploitation_ratio_2018
revenue_2022
net_result_2022
equity_2022
roe_2022
net_debt_2022
current_assets_2022
current_liabilities_2022
solvability_ratio_2022
gross_operating_ebitda_2022
gross_operating_ebitda_ratio_2022
gross_operating_ebitda_ratio
reimbursement_ratio_2022
robustness_ratio_2022
resultat_exploitation_ratio_2022
resultat_d_exploitation_2021
resultat_d_exploitation_2020
resultat_d_exploitation_2019
resultat_d_exploitation_2018
resultat_d_exploitation_2022
resultat_exploitation_ratio
net_result
current_assets
equity
current_liabilities
revenue
reimbursement_ratio
robustness_ratio
solvability_ratio
net_debt
gross_operating_ebitda
CAGR_18_22
RCI_2018
RCI_2019
RCI_2020
RCI_2021
RCI_2022
RCI
total_fonds
equity_costs

In [52]:
resultat_final = pd.merge(volume_ent, moyennes_par_ape, on='ape_code', how='inner')
resultat_final.head(20)
resultat_final.columns

NameError: name 'volume_ent' is not defined

In [53]:
RE_sup10 = resultat_final[resultat_final['resultat_exploitation_ratio'] > 0.1]
RE_sup10 = RE_sup10.sort_values('resultat_exploitation_ratio', ascending=False)
RE_sup10

NameError: name 'resultat_final' is not defined

In [54]:
RE_below0 = resultat_final[resultat_final['resultat_exploitation_ratio'] < 0]
RE_below0 = RE_below0.sort_values('resultat_exploitation_ratio', ascending=False)
RE_below0

NameError: name 'resultat_final' is not defined

In [55]:
#Si le RCI est supérieur au coût du capital, cela signifie que l'entreprise génère un rendement sur ses investissements qui est plus élevé que le coût de financement de ces investissements. C'est une indication que l'entreprise crée de la valeur.
#Si le RCI est inférieur au coût du capital, cela indique que l'entreprise ne génère pas suffisamment de rendement pour couvrir le coût de ses capitaux. Cela peut être un signe que l'entreprise détruit de la valeur.
entreprise_performante = nouveau_source_entreprise[nouveau_source_entreprise['RCI'] > 0]
entreprise_performante = nouveau_source_entreprise[nouveau_source_entreprise['RCI'] > nouveau_source_entreprise['equity_costs']]

In [56]:
entreprise_performante.head(5)

,estimated_revenue_estimated_revenue_2020,instagram_url,ape_code,indeed_about_content,banking_data_solde_credit_equipement,net_result_2018,cartography_liens_entreprises_personnes,derniere_mise_a_jour_rcs,banking_data_bdf_score,revenue_2020,...,RdtCpx_2020,RdtCpx_2021,RdtCpx_2022,RdtCpx,FRN_2018,FRN_2019,FRN_2020,FRN_2021,FRN_2022,FRN
0,8559262.0,https://www.instagram.com/cheznestorfrance,6820A,NaN,NaN,488597.0,", , , , ,",2023-09-15,NaN,8559262.0,...,0.143647,NaN,NaN,0.341562,1129607.0,978613.0,1916120.0,NaN,NaN,1.341447e+06
5,6900000.0,NaN,4673A,NaN,NaN,179247.0,", , , , , , , , , , , , , , , , , , ,",NaN,NaN,6900000.0,...,NaN,0.122245,0.119363,0.099953,0.0,1138180.0,NaN,1651480.0,2197871.0,9.298867e+05
7,49920479.0,https://www.instagram.com/marignan.immo/,4110A,NaN,NaN,32441024.0,", , , , , , , , , , , , , , , , , , , , , , , ...",NaN,NaN,49920479.0,...,0.110299,0.128634,NaN,0.153360,123295372.0,134636437.0,107061250.0,77801778.0,NaN,1.106987e+08
8,5752700.0,https://www.instagram.com/jalis_webagency/,6202A,NaN,NaN,184101.0,", , , , , , , , , , , , , , , , , , , , , , , ...",NaN,NaN,5752700.0,...,0.707936,0.966960,NaN,0.793083,2558375.0,2605473.0,3097014.0,3477992.0,NaN,2.934714e+06
10,5930008.0,NaN,7820Z,NaN,NaN,103132.0,", , ,",NaN,NaN,5930008.0,...,0.151795,0.318798,NaN,0.307077,3512439.0,3353235.0,3479171.0,3525791.0,NaN,3.467659e+06

In [57]:
source_entreprise.to_csv('base_source_filtree.csv', index='siren')

In [58]:
def renommer_colonnesmoy_selectionnees(dataframe, colonnes_a_renommer):
    # Créez un dictionnaire pour mapper les anciens noms aux nouveaux noms
    colonnes_renommees = {colonne: colonne + "_moy_sect" for colonne in colonnes_a_renommer}
    
    # Utilisez la méthode rename() pour renommer les colonnes sélectionnées du DataFrame
    dataframe.rename(columns=colonnes_renommees, inplace=True)
    
    return dataframe
colonnes_a_renommer=['capital', 'enrollment', 'last_number_of_employees',
       'employees_number_for_linkedin', 'revenue_2021', 'revenue_2020',
       'revenue_2019', 'revenue_2018', 'net_result_2021', 'equity_2021',
       'roe_2021', 'net_debt_2021', 'current_assets_2021',
       'current_liabilities_2021', 'solvability_ratio_2021',
       'gross_operating_ebitda_2021', 'gross_operating_ebitda_ratio_2021',
       'reimbursement_ratio_2021', 'robustness_ratio_2021', 'net_result_2020',
       'equity_2020', 'roe_2020', 'net_debt_2020', 'current_assets_2020',
       'current_liabilities_2020', 'solvability_ratio_2020',
       'gross_operating_ebitda_2020', 'gross_operating_ebitda_ratio_2020',
       'reimbursement_ratio_2020', 'robustness_ratio_2020', 'net_result_2019',
       'equity_2019', 'roe_2019', 'net_debt_2019', 'current_assets_2019',
       'current_liabilities_2019', 'solvability_ratio_2019',
       'gross_operating_ebitda_2019', 'gross_operating_ebitda_ratio_2019',
       'reimbursement_ratio_2019', 'robustness_ratio_2019', 'net_result_2018',
       'equity_2018', 'roe_2018', 'net_debt_2018', 'current_assets_2018',
       'current_liabilities_2018', 'solvability_ratio_2018',
       'gross_operating_ebitda_2018', 'gross_operating_ebitda_ratio_2018',
       'reimbursement_ratio_2018', 'robustness_ratio_2018',
       'growth_ratio_2021', 'growth_ratio_2020', 'growth_ratio_2019',
       'resultat_exploitation_ratio_2021', 'resultat_exploitation_ratio_2020',
       'resultat_exploitation_ratio_2019', 'resultat_exploitation_ratio_2018',
       'revenue_2022', 'net_result_2022', 'equity_2022', 'roe_2022',
       'net_debt_2022', 'current_assets_2022', 'current_liabilities_2022',
       'solvability_ratio_2022', 'gross_operating_ebitda_2022',
       'gross_operating_ebitda_ratio_2022', 'reimbursement_ratio_2022',
       'robustness_ratio_2022', 'growth_ratio_2022',
       'resultat_exploitation_ratio_2022', 'resultat_d_exploitation_2021',
       'resultat_d_exploitation_2020', 'resultat_d_exploitation_2019',
       'resultat_d_exploitation_2018', 'resultat_d_exploitation_2022',
       'resultat_exploitation_ratio', 'net_result', 'current_assets', 'equity',
       'current_liabilities', 'revenue', 'reimbursement_ratio',
       'robustness_ratio', 'solvability_ratio', 'net_debt',
       'gross_operating_ebitda','gross_operating_ebitda_ratio', 'CAGR_18_22', 'RCI_2018', 'RCI_2019',
       'RCI_2020', 'RCI_2021', 'RCI_2022', 'RCI', 'total_fonds',
       'equity_costs']
moyennes_par_secteur = renommer_colonnesmoy_selectionnees(moyennes_par_secteur, colonnes_a_renommer)

In [59]:
def renommer_colonnessum_selectionnees(dataframe, colonnes_a_renommer):
    # Créez un dictionnaire pour mapper les anciens noms aux nouveaux noms
    colonnes_renommees = {colonne: colonne + "_sum" for colonne in colonnes_a_renommer}
    
    # Utilisez la méthode rename() pour renommer les colonnes sélectionnées du DataFrame
    dataframe.rename(columns=colonnes_renommees, inplace=True)
    
    return dataframe

colonnes_a_renommer=['capital', 'enrollment', 'last_number_of_employees',
       'employees_number_for_linkedin', 'revenue_2021', 'revenue_2020',
       'revenue_2019', 'revenue_2018', 'net_result_2021', 'equity_2021',
       'roe_2021', 'net_debt_2021', 'current_assets_2021',
       'current_liabilities_2021', 'solvability_ratio_2021',
       'gross_operating_ebitda_2021', 'gross_operating_ebitda_ratio_2021',
       'reimbursement_ratio_2021', 'robustness_ratio_2021', 'net_result_2020',
       'equity_2020', 'roe_2020', 'net_debt_2020', 'current_assets_2020',
       'current_liabilities_2020', 'solvability_ratio_2020',
       'gross_operating_ebitda_2020', 'gross_operating_ebitda_ratio_2020',
       'reimbursement_ratio_2020', 'robustness_ratio_2020', 'net_result_2019',
       'equity_2019', 'roe_2019', 'net_debt_2019', 'current_assets_2019',
       'current_liabilities_2019', 'solvability_ratio_2019',
       'gross_operating_ebitda_2019', 'gross_operating_ebitda_ratio_2019',
       'reimbursement_ratio_2019', 'robustness_ratio_2019', 'net_result_2018',
       'equity_2018', 'roe_2018', 'net_debt_2018', 'current_assets_2018',
       'current_liabilities_2018', 'solvability_ratio_2018',
       'gross_operating_ebitda_2018', 'gross_operating_ebitda_ratio_2018',
       'reimbursement_ratio_2018', 'robustness_ratio_2018',
       'growth_ratio_2021', 'growth_ratio_2020', 'growth_ratio_2019',
       'resultat_exploitation_ratio_2021', 'resultat_exploitation_ratio_2020',
       'resultat_exploitation_ratio_2019', 'resultat_exploitation_ratio_2018',
       'revenue_2022', 'net_result_2022', 'equity_2022', 'roe_2022',
       'net_debt_2022', 'current_assets_2022', 'current_liabilities_2022',
       'solvability_ratio_2022', 'gross_operating_ebitda_2022',
       'gross_operating_ebitda_ratio_2022', 'reimbursement_ratio_2022',
       'robustness_ratio_2022', 'growth_ratio_2022',
       'resultat_exploitation_ratio_2022', 'resultat_d_exploitation_2021',
       'resultat_d_exploitation_2020', 'resultat_d_exploitation_2019',
       'resultat_d_exploitation_2018', 'resultat_d_exploitation_2022',
       'resultat_exploitation_ratio', 'net_result', 'current_assets', 'equity',
       'current_liabilities', 'revenue', 'reimbursement_ratio',
       'robustness_ratio', 'solvability_ratio', 'net_debt',
       'gross_operating_ebitda','gross_operating_ebitda_ratio', 'CAGR_18_22', 'RCI_2018', 'RCI_2019',
       'RCI_2020', 'RCI_2021', 'RCI_2022', 'RCI', 'total_fonds',
       'equity_costs']
total_par_secteur = renommer_colonnessum_selectionnees(total_par_secteur, colonnes_a_renommer)

In [60]:
moyennes_par_secteur.columns

Index(['capital_moy_sect', 'enrollment_moy_sect',
       'last_number_of_employees_moy_sect',
       'employees_number_for_linkedin_moy_sect', 'revenue_2021_moy_sect',
       'revenue_2020_moy_sect', 'revenue_2019_moy_sect',
       'revenue_2018_moy_sect', 'net_result_2021_moy_sect',
       'equity_2021_moy_sect', 'roe_2021_moy_sect', 'net_debt_2021_moy_sect',
       'current_assets_2021_moy_sect', 'current_liabilities_2021_moy_sect',
       'solvability_ratio_2021_moy_sect',
       'gross_operating_ebitda_2021_moy_sect',
       'gross_operating_ebitda_ratio_2021_moy_sect',
       'reimbursement_ratio_2021_moy_sect', 'robustness_ratio_2021_moy_sect',
       'net_result_2020_moy_sect', 'equity_2020_moy_sect', 'roe_2020_moy_sect',
       'net_debt_2020_moy_sect', 'current_assets_2020_moy_sect',
       'current_liabilities_2020_moy_sect', 'solvability_ratio_2020_moy_sect',
       'gross_operating_ebitda_2020_moy_sect',
       'gross_operating_ebitda_ratio_2020_moy_sect',
       'reimbursement_ratio_2020_moy_sect', 'robustness_ratio_2020_moy_sect',
       'net_result_2019_moy_sect', 'equity_2019_moy_sect', 'roe_2019_moy_sect',
       'net_debt_2019_moy_sect', 'current_assets_2019_moy_sect',
       'current_liabilities_2019_moy_sect', 'solvability_ratio_2019_moy_sect',
       'gross_operating_ebitda_2019_moy_sect',
       'gross_operating_ebitda_ratio_2019_moy_sect',
       'reimbursement_ratio_2019_moy_sect', 'robustness_ratio_2019_moy_sect',
       'net_result_2018_moy_sect', 'equity_2018_moy_sect', 'roe_2018_moy_sect',
       'net_debt_2018_moy_sect', 'current_assets_2018_moy_sect',
       'current_liabilities_2018_moy_sect', 'solvability_ratio_2018_moy_sect',
       'gross_operating_ebitda_2018_moy_sect',
       'gross_operating_ebitda_ratio_2018_moy_sect',
       'reimbursement_ratio_2018_moy_sect', 'robustness_ratio_2018_moy_sect',
       'growth_ratio_2021_moy_sect', 'growth_ratio_2020_moy_sect',
       'growth_ratio_2019_moy_sect',
       'resultat_exploitation_ratio_2021_moy_sect',
       'resultat_exploitation_ratio_2020_moy_sect',
       'resultat_exploitation_ratio_2019_moy_sect',
       'resultat_exploitation_ratio_2018_moy_sect', 'revenue_2022_moy_sect',
       'net_result_2022_moy_sect', 'equity_2022_moy_sect', 'roe_2022_moy_sect',
       'net_debt_2022_moy_sect', 'current_assets_2022_moy_sect',
       'current_liabilities_2022_moy_sect', 'solvability_ratio_2022_moy_sect',
       'gross_operating_ebitda_2022_moy_sect',
       'gross_operating_ebitda_ratio_2022_moy_sect',
       'gross_operating_ebitda_ratio_moy_sect',
       'reimbursement_ratio_2022_moy_sect', 'robustness_ratio_2022_moy_sect',
       'resultat_exploitation_ratio_2022_moy_sect',
       'resultat_d_exploitation_2021_moy_sect',
       'resultat_d_exploitation_2020_moy_sect',
       'resultat_d_exploitation_2019_moy_sect',
       'resultat_d_exploitation_2018_moy_sect',
       'resultat_d_exploitation_2022_moy_sect',
       'resultat_exploitation_ratio_moy_sect', 'net_result_moy_sect',
       'current_assets_moy_sect', 'equity_moy_sect',
       'current_liabilities_moy_sect', 'revenue_moy_sect',
       'reimbursement_ratio_moy_sect', 'robustness_ratio_moy_sect',
       'solvability_ratio_moy_sect', 'net_debt_moy_sect',
       'gross_operating_ebitda_moy_sect', 'CAGR_18_22_moy_sect',
       'RCI_2018_moy_sect', 'RCI_2019_moy_sect', 'RCI_2020_moy_sect',
       'RCI_2021_moy_sect', 'RCI_2022_moy_sect', 'RCI_moy_sect',
       'total_fonds_moy_sect', 'equity_costs_moy_sect'],
      dtype='object')

In [61]:
total_par_secteur.columns

Index(['capital_sum', 'enrollment_sum', 'last_number_of_employees_sum',
       'employees_number_for_linkedin_sum', 'revenue_2021_sum',
       'revenue_2020_sum', 'revenue_2019_sum', 'revenue_2018_sum',
       'net_result_2021_sum', 'equity_2021_sum', 'roe_2021_sum',
       'net_debt_2021_sum', 'current_assets_2021_sum',
       'current_liabilities_2021_sum', 'solvability_ratio_2021_sum',
       'gross_operating_ebitda_2021_sum',
       'gross_operating_ebitda_ratio_2021_sum', 'reimbursement_ratio_2021_sum',
       'robustness_ratio_2021_sum', 'net_result_2020_sum', 'equity_2020_sum',
       'roe_2020_sum', 'net_debt_2020_sum', 'current_assets_2020_sum',
       'current_liabilities_2020_sum', 'solvability_ratio_2020_sum',
       'gross_operating_ebitda_2020_sum',
       'gross_operating_ebitda_ratio_2020_sum', 'reimbursement_ratio_2020_sum',
       'robustness_ratio_2020_sum', 'net_result_2019_sum', 'equity_2019_sum',
       'roe_2019_sum', 'net_debt_2019_sum', 'current_assets_2019_sum',
       'current_liabilities_2019_sum', 'solvability_ratio_2019_sum',
       'gross_operating_ebitda_2019_sum',
       'gross_operating_ebitda_ratio_2019_sum', 'reimbursement_ratio_2019_sum',
       'robustness_ratio_2019_sum', 'net_result_2018_sum', 'equity_2018_sum',
       'roe_2018_sum', 'net_debt_2018_sum', 'current_assets_2018_sum',
       'current_liabilities_2018_sum', 'solvability_ratio_2018_sum',
       'gross_operating_ebitda_2018_sum',
       'gross_operating_ebitda_ratio_2018_sum', 'reimbursement_ratio_2018_sum',
       'robustness_ratio_2018_sum', 'growth_ratio_2021_sum',
       'growth_ratio_2020_sum', 'growth_ratio_2019_sum',
       'resultat_exploitation_ratio_2021_sum',
       'resultat_exploitation_ratio_2020_sum',
       'resultat_exploitation_ratio_2019_sum',
       'resultat_exploitation_ratio_2018_sum', 'revenue_2022_sum',
       'net_result_2022_sum', 'equity_2022_sum', 'roe_2022_sum',
       'net_debt_2022_sum', 'current_assets_2022_sum',
       'current_liabilities_2022_sum', 'solvability_ratio_2022_sum',
       'gross_operating_ebitda_2022_sum',
       'gross_operating_ebitda_ratio_2022_sum',
       'gross_operating_ebitda_ratio_sum', 'reimbursement_ratio_2022_sum',
       'robustness_ratio_2022_sum', 'resultat_exploitation_ratio_2022_sum',
       'resultat_d_exploitation_2021_sum', 'resultat_d_exploitation_2020_sum',
       'resultat_d_exploitation_2019_sum', 'resultat_d_exploitation_2018_sum',
       'resultat_d_exploitation_2022_sum', 'resultat_exploitation_ratio_sum',
       'net_result_sum', 'current_assets_sum', 'equity_sum',
       'current_liabilities_sum', 'revenue_sum', 'reimbursement_ratio_sum',
       'robustness_ratio_sum', 'solvability_ratio_sum', 'net_debt_sum',
       'gross_operating_ebitda_sum', 'CAGR_18_22_sum', 'RCI_2018_sum',
       'RCI_2019_sum', 'RCI_2020_sum', 'RCI_2021_sum', 'RCI_2022_sum',
       'RCI_sum', 'total_fonds_sum', 'equity_costs_sum'],
      dtype='object')

In [62]:
secteur_db = pd.merge(moyennes_par_secteur, total_par_secteur, on='ape_code', how='inner')

C:\Users\chris\AppData\Local\Temp\ipykernel_7240\2814017385.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  secteur_db = pd.merge(moyennes_par_secteur, total_par_secteur, on='ape_code', how='inner')

In [34]:

secteur_db.to_csv('base_secteur_initiale.csv', index='ape_code')